import type {
  Niche, StyleOption, PlatformOption, LanguageOption, AnimationOption,
  FontOption, StructureOption, FunctionalityOption, ObjectiveOption,
  ContractTypeOption, ClauseOption, PaymentMethodOption, Plan, NavItem,
  WizardStepConfig
} from '../types';

export const PLANS: Plan[] = [
  {
    id: 'none', name: 'Sem plano', price: 0, currency: 'BRL', period: 'monthly',
    features: [
      'Acesso ao dashboard', 'Visualização de funcionalidades', 'Sem geração de prompts',
      'Sem contratos', 'Sem propostas', 'Sem orçamentos', 'Sem briefings',
      'Sem IA', 'Sem exportação',
    ],
    highlighted: false, color: '#6B7280', icon: 'Eye',
    promptLimit: 0, contractLimit: 0, projectLimit: 0, teamMembers: 0,
    analytics: false, prioritySupport: false,
  },
  {
    id: 'starter', name: 'Starter', price: 29.90, currency: 'BRL', period: 'monthly',
    features: [
      '100 prompts/mês', '20 contratos/mês', '20 nichos', 'Histórico completo',
      'Favoritos', 'Projetos', 'Exportação TXT', 'Exportação Markdown',
      'Português e Inglês', 'Suporte por Email', 'Atualizações constantes',
    ],
    highlighted: false, color: '#8B5CF6', icon: 'Rocket',
    promptLimit: 100, contractLimit: 20, projectLimit: 5, teamMembers: 1,
    analytics: false, prioritySupport: false,
  },
  {
    id: 'pro', name: 'Pro', price: 47.00, currency: 'BRL', period: 'monthly',
    features: [
      'Prompts ilimitados', 'Contratos ilimitados', 'Projetos ilimitados',
      'Histórico ilimitado', 'Favoritos ilimitados', 'Mais de 100 nichos',
      'Mais estilos e animações', 'Biblioteca Premium', 'Exportação PDF',
      'Exportação DOCX', 'Upload PDF/DOCX', 'IA analisa Briefings',
      'IA melhora prompts', 'IA corrige prompts', 'IA otimiza prompts',
      'IA gera versões alternativas', 'Modelos Premium', 'Contratos Premium',
      'Propostas Premium', 'Orçamentos Premium', 'Briefings Premium',
      'SEO Avançado', 'UX/UI Premium', 'Suporte Prioritário', 'Novidades antecipadas',
    ],
    highlighted: true, color: '#A855F7', icon: 'Star',
    promptLimit: Infinity, contractLimit: Infinity, projectLimit: Infinity, teamMembers: 1,
    analytics: true, prioritySupport: true,
  },
];

export const WIZARD_STEPS: WizardStepConfig[] = [
  { id: 1, title: 'Nicho', description: 'Escolha o nicho do projeto', icon: 'Layers', component: 'NicheStep' },
];

export const NICHES: Niche[] = [
  { id: 'fitness', label: 'Academia', labelEn: 'Gym', icon: 'Dumbbell', emoji: '💪', description: 'Academias e centros de treinamento', color: '#EF4444' },
  { id: 'beauty', label: 'Barbearia', labelEn: 'Barbershop', icon: 'Scissors', emoji: '💈', description: 'Barbearias e cuidados masculinos', color: '#F97316' },
  { id: 'beauty', label: 'Salão de Beleza', labelEn: 'Beauty Salon', icon: 'Sparkles', emoji: '💇‍♀️', description: 'Salões e estética', color: '#EC4899' },
  { id: 'health', label: 'Clínica Médica', labelEn: 'Medical Clinic', icon: 'Stethoscope', emoji: '🏥', description: 'Consultórios e clínicas', color: '#10B981' },
  { id: 'health', label: 'Clínica Odontológica', labelEn: 'Dental Clinic', icon: 'Tooth', emoji: '🦷', description: 'Consultórios odontológicos', color: '#06B6D4' },
  { id: 'health', label: 'Psicologia', labelEn: 'Psychology', icon: 'Brain', emoji: '🧠', description: 'Profissionais de saúde mental', color: '#8B5CF6' },
  { id: 'health', label: 'Nutrição', labelEn: 'Nutrition', icon: 'Apple', emoji: '🥗', description: 'Nutricionistas e dietistas', color: '#22C55E' },
  { id: 'real-estate', label: 'Imobiliária', labelEn: 'Real Estate', icon: 'Building', emoji: '🏠', description: 'Corretoras e imobiliárias', color: '#3B82F6' },
  { id: 'food', label: 'Restaurante', labelEn: 'Restaurant', icon: 'UtensilsCrossed', emoji: '🍽️', description: 'Restaurantes e gastronomia', color: '#F59E0B' },
  { id: 'food', label: 'Pizzaria', labelEn: 'Pizzeria', icon: 'Pizza', emoji: '🍕', description: 'Pizzarias e delivery', color: '#EF4444' },
  { id: 'food', label: 'Hamburgueria', labelEn: 'Burger Shop', icon: 'Beef', emoji: '🍔', description: 'Hamburguerias artesanais', color: '#92400E' },
  { id: 'food', label: 'Cafeteria', labelEn: 'Coffee Shop', icon: 'Coffee', emoji: '☕', description: 'Cafeterias e confeitarias', color: '#78350F' },
  { id: 'fashion', label: 'Loja de Roupas', labelEn: 'Clothing Store', icon: 'Shirt', emoji: '👕', description: 'Moda e vestuário', color: '#EC4899' },
  { id: 'fashion', label: 'Loja de Calçados', labelEn: 'Shoe Store', icon: 'Footprints', emoji: '👟', description: 'Calçados e acessórios', color: '#8B5CF6' },
  { id: 'ecommerce', label: 'E-commerce', labelEn: 'E-commerce', icon: 'ShoppingCart', emoji: '🛒', description: 'Lojas virtuais completas', color: '#F97316' },
  { id: 'law', label: 'Advocacia', labelEn: 'Law Firm', icon: 'Scale', emoji: '⚖️', description: 'Escritórios de advocacia', color: '#1E40AF' },
  { id: 'finance', label: 'Contabilidade', labelEn: 'Accounting', icon: 'Calculator', emoji: '📊', description: 'Escritórios contábeis', color: '#059669' },
  { id: 'finance', label: 'Corretora de Seguros', labelEn: 'Insurance Broker', icon: 'Shield', emoji: '🛡️', description: 'Corretoras e seguros', color: '#2563EB' },
  { id: 'marketing', label: 'Agência de Marketing', labelEn: 'Marketing Agency', icon: 'Megaphone', emoji: '📢', description: 'Agências de marketing digital', color: '#D946EF' },
  { id: 'photography', label: 'Portfólio', labelEn: 'Portfolio', icon: 'Image', emoji: '📸', description: 'Portfólios profissionais', color: '#A855F7' },
  { id: 'saas', label: 'SaaS', labelEn: 'SaaS', icon: 'Cloud', emoji: '☁️', description: 'Software como serviço', color: '#06B6D4', premium: true },
  { id: 'tech', label: 'Startup', labelEn: 'Startup', icon: 'Rocket', emoji: '🚀', description: 'Startups inovadoras', color: '#F59E0B', premium: true },
  { id: 'tech', label: 'Empresa de Tecnologia', labelEn: 'Tech Company', icon: 'Monitor', emoji: '💻', description: 'Empresas de TI', color: '#3B82F6', premium: true },
  { id: 'travel', label: 'Hotel', labelEn: 'Hotel', icon: 'Hotel', emoji: '🏨', description: 'Hotéis e hospedagem', color: '#8B5CF6', premium: true },
  { id: 'travel', label: 'Turismo', labelEn: 'Tourism', icon: 'Globe', emoji: '✈️', description: 'Agências de turismo', color: '#0EA5E9', premium: true },
  { id: 'education', label: 'Escola', labelEn: 'School', icon: 'GraduationCap', emoji: '🏫', description: 'Escolas e colégios', color: '#10B981', premium: true },
  { id: 'education', label: 'Curso Online', labelEn: 'Online Course', icon: 'Video', emoji: '🎓', description: 'Cursos e plataformas EAD', color: '#D946EF', premium: true },
  { id: 'automotive', label: 'Oficina Mecânica', labelEn: 'Auto Repair', icon: 'Wrench', emoji: '🔧', description: 'Oficinas e reparos', color: '#6B7280', premium: true },
  { id: 'automotive', label: 'Auto Center', labelEn: 'Auto Center', icon: 'Car', emoji: '🚗', description: 'Centros automotivos', color: '#1F2937', premium: true },
  { id: 'automotive', label: 'Lava Jato', labelEn: 'Car Wash', icon: 'Droplets', emoji: '🚿', description: 'Lava jatos e estética automotiva', color: '#0284C7', premium: true },
  { id: 'automotive', label: 'Concessionária', labelEn: 'Dealership', icon: 'CarFront', emoji: '🚘', description: 'Concessionárias de veículos', color: '#2563EB', premium: true },
  { id: 'real-estate', label: 'Incorporadora', labelEn: 'Real Estate Developer', icon: 'Building2', emoji: '🏗️', description: 'Incorporadoras e construtoras', color: '#DC2626', premium: true },
  { id: 'real-estate', label: 'Condomínio', labelEn: 'Condominium', icon: 'DoorOpen', emoji: '🏢', description: 'Condomínios residenciais', color: '#7C3AED', premium: true },
  { id: 'real-estate', label: 'Arquiteto', labelEn: 'Architect', icon: 'PencilRuler', emoji: '📐', description: 'Escritórios de arquitetura', color: '#F59E0B', premium: true },
  { id: 'real-estate', label: 'Decoração', labelEn: 'Interior Design', icon: 'Sofa', emoji: '🛋️', description: 'Design de interiores', color: '#EC4899', premium: true },
  { id: 'food', label: 'Padaria', labelEn: 'Bakery', icon: 'Bread', emoji: '🥖', description: 'Padarias e confeitarias', color: '#92400E', premium: true },
  { id: 'food', label: 'Sorveteria', labelEn: 'Ice Cream Shop', icon: 'IceCream', emoji: '🍦', description: 'Sorveterias e gelaterias', color: '#F472B6', premium: true },
  { id: 'food', label: 'Açaí', labelEn: 'Açaí Shop', icon: 'Fruit', emoji: '🫐', description: 'Açaí e bowls saudáveis', color: '#7C3AED', premium: true },
  { id: 'food', label: 'Mercado', labelEn: 'Grocery Store', icon: 'ShoppingBasket', emoji: '🛒', description: 'Supermercados e mercearias', color: '#22C55E', premium: true },
  { id: 'food', label: 'Adega', labelEn: 'Winery', icon: 'Wine', emoji: '🍷', description: 'Adegas e lojas de vinhos', color: '#7F1D1D', premium: true },
  { id: 'food', label: 'Churrascaria', labelEn: 'Steakhouse', icon: 'Flame', emoji: '🥩', description: 'Churrascarias e parrillas', color: '#B91C1C', premium: true },
  { id: 'food', label: 'Sushi', labelEn: 'Sushi Bar', icon: 'Fish', emoji: '🍣', description: 'Restaurantes japoneses', color: '#0F766E', premium: true },
  { id: 'food', label: 'Petiscaria', labelEn: 'Pub Food', icon: 'Beer', emoji: '🍻', description: 'Bares e petiscarias', color: '#A16207', premium: true },
  { id: 'health', label: 'Veterinário', labelEn: 'Veterinary', icon: 'Cat', emoji: '🐾', description: 'Clínicas veterinárias', color: '#0D9488', premium: true },
  { id: 'health', label: 'Fisioterapia', labelEn: 'Physical Therapy', icon: 'Bone', emoji: '🦴', description: 'Clínicas de fisioterapia', color: '#0891B2', premium: true },
  { id: 'health', label: 'Oftalmologia', labelEn: 'Ophthalmology', icon: 'Eye', emoji: '👁️', description: 'Consultórios oftalmológicos', color: '#0284C7', premium: true },
  { id: 'health', label: 'Dermatologia', labelEn: 'Dermatology', icon: 'Droplets', emoji: '🧴', description: 'Clínicas dermatológicas', color: '#DB2777', premium: true },
  { id: 'health', label: 'Fonoaudiologia', labelEn: 'Speech Therapy', icon: 'Ear', emoji: '👂', description: 'Clínicas de fonoaudiologia', color: '#7C3AED', premium: true },
  { id: 'health', label: 'Cardiologia', labelEn: 'Cardiology', icon: 'HeartPulse', emoji: '❤️', description: 'Consultórios cardiológicos', color: '#DC2626', premium: true },
  { id: 'health', label: 'Pediatria', labelEn: 'Pediatrics', icon: 'Baby', emoji: '👶', description: 'Consultórios pediátricos', color: '#0EA5E9', premium: true },
  { id: 'health', label: 'Acupuntura', labelEn: 'Acupuncture', icon: 'Needle', emoji: '🪡', description: 'Terapias orientais', color: '#10B981', premium: true },
  { id: 'beauty', label: 'Clínica de Estética', labelEn: 'Aesthetics Clinic', icon: 'Wand', emoji: '✨', description: 'Clínicas de estética avançada', color: '#EC4899', premium: true },
  { id: 'beauty', label: 'Depilação', labelEn: 'Hair Removal', icon: 'Zap', emoji: '⚡', description: 'Centros de depilação', color: '#D946EF', premium: true },
  { id: 'beauty', label: 'Tatuagem', labelEn: 'Tattoo Studio', icon: 'Pen', emoji: '🖊️', description: 'Estúdios de tatuagem', color: '#1F2937', premium: true },
  { id: 'beauty', label: 'Massoterapia', labelEn: 'Massage Therapy', icon: 'Hand', emoji: '💆', description: 'Centros de massagem', color: '#A855F7', premium: true },
  { id: 'beauty', label: 'Perfumaria', labelEn: 'Perfumery', icon: 'Flower2', emoji: '🌸', description: 'Lojas de perfumes', color: '#F472B6', premium: true },
  { id: 'fitness', label: 'CrossFit', labelEn: 'CrossFit', icon: 'Flame', emoji: '🔥', description: 'Box de CrossFit', color: '#DC2626', premium: true },
  { id: 'fitness', label: 'Pilates', labelEn: 'Pilates Studio', icon: 'Accessibility', emoji: '🧘', description: 'Estúdios de pilates', color: '#8B5CF6', premium: true },
  { id: 'fitness', label: 'Yoga', labelEn: 'Yoga Studio', icon: 'Gem', emoji: '🧘‍♀️', description: 'Estúdios de yoga', color: '#F59E0B', premium: true },
  { id: 'fitness', label: 'Esporte', labelEn: 'Sports', icon: 'Trophy', emoji: '🏆', description: 'Clubes e centros esportivos', color: '#2563EB', premium: true },
  { id: 'fashion', label: 'Joalheria', labelEn: 'Jewelry', icon: 'Gem', emoji: '💎', description: 'Joalherias e bijuterias', color: '#F59E0B', premium: true },
  { id: 'fashion', label: 'Ótica', labelEn: 'Optical Store', icon: 'Glasses', emoji: '👓', description: 'Óticas e relojoarias', color: '#0F766E', premium: true },
  { id: 'fashion', label: 'Moda Infantil', labelEn: 'Kids Fashion', icon: 'Baby', emoji: '👶', description: 'Moda para crianças', color: '#0EA5E9', premium: true },
  { id: 'fashion', label: 'Moda Fitness', labelEn: 'Activewear', icon: 'Dumbbell', emoji: '🏃', description: 'Moda esportiva', color: '#7C3AED', premium: true },
  { id: 'fashion', label: 'Moda Íntima', labelEn: 'Lingerie', icon: 'Heart', emoji: '💕', description: 'Lingerie e moda praia', color: '#DB2777', premium: true },
  { id: 'fashion', label: 'Moda Masculina', labelEn: 'Men Fashion', icon: 'Shirt', emoji: '👔', description: 'Moda masculina premium', color: '#1E3A5F', premium: true },
  { id: 'fashion', label: 'Bolsas e Acessórios', labelEn: 'Bags & Accessories', icon: 'Baggage', emoji: '👜', description: 'Lojas de acessórios', color: '#78350F', premium: true },
  { id: 'food', label: 'Marmitaria', labelEn: 'Meal Prep', icon: 'Package', emoji: '📦', description: 'Marmitas e alimentação saudável', color: '#16A34A', premium: true },
  { id: 'food', label: 'Food Truck', labelEn: 'Food Truck', icon: 'Truck', emoji: '🚚', description: 'Food trucks e trailers', color: '#EA580C', premium: true },
  { id: 'food', label: 'Doceria', labelEn: 'Candy Shop', icon: 'Candy', emoji: '🍬', description: 'Doces e sobremesas', color: '#F472B6', premium: true },
  { id: 'pets', label: 'Pet Shop', labelEn: 'Pet Shop', icon: 'Dog', emoji: '🐕', description: 'Lojas de animais e pet care', color: '#F97316', premium: true },
  { id: 'food', label: 'Distribuidora', labelEn: 'Distributor', icon: 'Truck', emoji: '🚛', description: 'Distribuidoras alimentícias', color: '#475569', premium: true },
  { id: 'law', label: 'Cartório', labelEn: 'Notary', icon: 'FileText', emoji: '📜', description: 'Cartórios e tabelionatos', color: '#78350F', premium: true },
  { id: 'law', label: 'Consultoria Jurídica', labelEn: 'Legal Consulting', icon: 'BookOpen', emoji: '📚', description: 'Consultorias jurídicas', color: '#1E40AF', premium: true },
  { id: 'law', label: 'Justiça Trabalhista', labelEn: 'Labor Law', icon: 'Users', emoji: '👥', description: 'Direito trabalhista', color: '#B91C1C', premium: true },
  { id: 'finance', label: 'Fintech', labelEn: 'Fintech', icon: 'Banknote', emoji: '💰', description: 'Startups financeiras', color: '#059669', premium: true },
  { id: 'finance', label: 'Banco Digital', labelEn: 'Digital Bank', icon: 'Landmark', emoji: '🏦', description: 'Bancos e instituições financeiras', color: '#2563EB', premium: true },
  { id: 'finance', label: 'Investimentos', labelEn: 'Investments', icon: 'TrendingUp', emoji: '📈', description: 'Consultorias de investimento', color: '#16A34A', premium: true },
  { id: 'finance', label: 'Câmbio', labelEn: 'Currency Exchange', icon: 'ArrowLeftRight', emoji: '🔄', description: 'Casas de câmbio', color: '#0891B2', premium: true },
  { id: 'education', label: 'Universidade', labelEn: 'University', icon: 'GraduationCap', emoji: '🎓', description: 'Universidades e faculdades', color: '#7C3AED', premium: true },
  { id: 'education', label: 'Idiomas', labelEn: 'Language School', icon: 'Languages', emoji: '🗣️', description: 'Escolas de idiomas', color: '#06B6D4', premium: true },
  { id: 'education', label: 'Música', labelEn: 'Music School', icon: 'Music', emoji: '🎵', description: 'Escolas de música', color: '#D946EF', premium: true },
  { id: 'education', label: 'Dança', labelEn: 'Dance School', icon: 'Music4', emoji: '💃', description: 'Escolas de dança', color: '#EC4899', premium: true },
  { id: 'education', label: 'Reforço Escolar', labelEn: 'Tutoring', icon: 'BookOpenText', emoji: '📖', description: 'Aulas particulares', color: '#F59E0B', premium: true },
  { id: 'education', label: 'Curso Técnico', labelEn: 'Technical Course', icon: 'Wrench', emoji: '🔧', description: 'Cursos profissionalizantes', color: '#0891B2', premium: true },
  { id: 'education', label: 'Auto Escola', labelEn: 'Driving School', icon: 'Car', emoji: '🚗', description: 'Auto escolas e CFCs', color: '#DC2626', premium: true },
  { id: 'tech', label: 'Agência de Tecnologia', labelEn: 'Tech Agency', icon: 'Code', emoji: '💻', description: 'Agências de desenvolvimento', color: '#2563EB', premium: true },
  { id: 'tech', label: 'Game Dev', labelEn: 'Game Development', icon: 'Gamepad2', emoji: '🎮', description: 'Estúdios de games', color: '#7C3AED', premium: true },
  { id: 'tech', label: 'Cibersegurança', labelEn: 'Cybersecurity', icon: 'Shield', emoji: '🔒', description: 'Empresas de segurança digital', color: '#DC2626', premium: true },
  { id: 'tech', label: 'Inteligência Artificial', labelEn: 'Artificial Intelligence', icon: 'BrainCircuit', emoji: '🤖', description: 'Empresas de IA', color: '#A855F7', premium: true },
  { id: 'tech', label: 'Blockchain', labelEn: 'Blockchain', icon: 'Hexagon', emoji: '⛓️', description: 'Blockchain e criptomoedas', color: '#F59E0B', premium: true },
  { id: 'tech', label: 'SaaS B2B', labelEn: 'B2B SaaS', icon: 'Cloud', emoji: '☁️', description: 'SaaS para empresas', color: '#0284C7', premium: true },
  { id: 'tech', label: 'IoT', labelEn: 'IoT', icon: 'Cpu', emoji: '🔌', description: 'Internet das Coisas', color: '#0D9488', premium: true },
  { id: 'tech', label: 'Data Science', labelEn: 'Data Science', icon: 'Database', emoji: '📊', description: 'Análise e ciência de dados', color: '#8B5CF6', premium: true },
  { id: 'travel', label: 'Pousada', labelEn: 'Inn', icon: 'House', emoji: '🏡', description: 'Pousadas e chalés', color: '#0D9488', premium: true },
  { id: 'travel', label: 'Resort', labelEn: 'Resort', icon: 'Umbrella', emoji: '🏖️', description: 'Resorts all-inclusive', color: '#0EA5E9', premium: true },
  { id: 'travel', label: 'Agência de Viagem', labelEn: 'Travel Agency', icon: 'Plane', emoji: '✈️', description: 'Agências de viagens', color: '#2563EB', premium: true },
  { id: 'travel', label: 'Camping', labelEn: 'Camping', icon: 'Tent', emoji: '🏕️', description: 'Campings e glamping', color: '#16A34A', premium: true },
  { id: 'travel', label: 'Aluguel Temporada', labelEn: 'Vacation Rental', icon: 'Key', emoji: '🔑', description: 'Aluguel por temporada', color: '#F97316', premium: true },
  { id: 'marketing', label: 'Social Media', labelEn: 'Social Media Agency', icon: 'Share2', emoji: '📱', description: 'Agências de mídias sociais', color: '#EC4899', premium: true },
  { id: 'marketing', label: 'SEO', labelEn: 'SEO Agency', icon: 'Search', emoji: '🔍', description: 'Agências de SEO', color: '#059669', premium: true },
  { id: 'marketing', label: 'Growth', labelEn: 'Growth Marketing', icon: 'TrendingUp', emoji: '📈', description: 'Growth marketing', color: '#D946EF', premium: true },
  { id: 'marketing', label: 'Influencer', labelEn: 'Influencer', icon: 'Camera', emoji: '📸', description: 'Gestão de influenciadores', color: '#F59E0B', premium: true },
  { id: 'photography', label: 'Filmagem', labelEn: 'Videography', icon: 'Video', emoji: '🎥', description: 'Produtoras de vídeo', color: '#DC2626', premium: true },
  { id: 'photography', label: 'Casamentos', labelEn: 'Wedding Photography', icon: 'Heart', emoji: '💒', description: 'Fotografia de casamentos', color: '#F472B6', premium: true },
  { id: 'photography', label: 'Drone', labelEn: 'Drone Services', icon: 'Plane', emoji: '🛸', description: 'Serviços com drones', color: '#0891B2', premium: true },
  { id: 'servicos', label: 'Hotel para Pets', labelEn: 'Pet Hotel', icon: 'Dog', emoji: '🐶', description: 'Hotéis e creches para pets', color: '#F97316', premium: true },
  { id: 'servicos', label: 'Lavanderia', labelEn: 'Laundry', icon: 'Shirt', emoji: '👔', description: 'Lavanderias e tinturarias', color: '#6B7280', premium: true },
  { id: 'servicos', label: 'Segurança', labelEn: 'Security', icon: 'ShieldAlert', emoji: '🛡️', description: 'Empresas de segurança', color: '#1E3A5F', premium: true },
  { id: 'servicos', label: 'Limpeza', labelEn: 'Cleaning Services', icon: 'SprayCan', emoji: '🧹', description: 'Serviços de limpeza', color: '#0EA5E9', premium: true },
  { id: 'servicos', label: 'Jardinagem', labelEn: 'Gardening', icon: 'Leaf', emoji: '🌿', description: 'Paisagismo e jardinagem', color: '#16A34A', premium: true },
  { id: 'servicos', label: 'Dedetizadora', labelEn: 'Pest Control', icon: 'Bug', emoji: '🐛', description: 'Controle de pragas', color: '#78350F', premium: true },
  { id: 'servicos', label: 'Mudanças', labelEn: 'Moving Company', icon: 'Truck', emoji: '🚚', description: 'Empresas de mudança', color: '#2563EB', premium: true },
  { id: 'servicos', label: 'Chaveiro', labelEn: 'Locksmith', icon: 'KeyRound', emoji: '🔐', description: 'Chaveiros 24h', color: '#92400E', premium: true },
  { id: 'servicos', label: 'Borracheiro', labelEn: 'Tire Shop', icon: 'Circle', emoji: '⚙️', description: 'Borracharias e pneus', color: '#1F2937', premium: true },
  { id: 'servicos', label: 'Assistência Técnica', labelEn: 'Tech Support', icon: 'Wrench', emoji: '🔧', description: 'Assistência de eletrônicos', color: '#0891B2', premium: true },
  { id: 'servicos', label: 'Funilaria', labelEn: 'Auto Body Shop', icon: 'Car', emoji: '🚗', description: 'Funilarias e pintura', color: '#B91C1C', premium: true },
  { id: 'servicos', label: 'Instalação Elétrica', labelEn: 'Electrical Services', icon: 'Zap', emoji: '⚡', description: 'Eletricistas e instalações', color: '#F59E0B', premium: true },
  { id: 'servicos', label: 'Encanador', labelEn: 'Plumbing', icon: 'Droplets', emoji: '🔧', description: 'Serviços hidráulicos', color: '#06B6D4', premium: true },
  { id: 'celulares', label: 'Loja de Celulares', labelEn: 'Cell Phone Store', icon: 'Smartphone', emoji: '📱', description: 'Venda de smartphones, acessórios e assistência técnica', color: '#8B5CF6', premium: true },
];

export const STYLES: StyleOption[] = [
  { id: 'minimalista', label: 'Minimalista', labelEn: 'Minimalist', icon: 'CircleDot', description: 'Limpo, espaçoso e focado no conteúdo', preview: 'minimal', category: 'estilo' },
  { id: 'apple', label: 'Estilo Apple', labelEn: 'Apple Style', icon: 'Apple', description: 'Premium, minimalista com tipografia impecável', preview: 'apple', category: 'estilo', premium: true },
  { id: 'premium', label: 'Premium', labelEn: 'Premium', icon: 'Gem', description: 'Design luxuoso com detalhes sofisticados', preview: 'premium', category: 'estilo', premium: true },
  { id: 'corporativo', label: 'Corporativo', labelEn: 'Corporate', icon: 'Briefcase', description: 'Visual profissional e sóbrio', preview: 'corporate', category: 'estilo' },
  { id: 'elegante', label: 'Elegante', labelEn: 'Elegant', icon: 'Feather', description: 'Refinado com tipografia clássica', preview: 'elegant', category: 'estilo' },
  { id: 'luxuoso', label: 'Luxuoso', labelEn: 'Luxurious', icon: 'Crown', description: 'Alto padrão com detalhes dourados', preview: 'luxury', category: 'estilo' },
  { id: 'futurista', label: 'Futurista', labelEn: 'Futuristic', icon: 'Rocket', description: 'Design com linhas e grids futuristas', preview: 'futuristic', category: 'estilo' },
  { id: 'cyberpunk', label: 'Cyberpunk', labelEn: 'Cyberpunk', icon: 'Cpu', description: 'Futurista com vibe cyberpunk', preview: 'cyberpunk', category: 'estilo' },
  { id: 'neon', label: 'Neon', labelEn: 'Neon', icon: 'Zap', description: 'Cores vibrantes e efeitos neon', preview: 'neon', category: 'estilo' },
  { id: 'glassmorphism', label: 'Glassmorphism', labelEn: 'Glassmorphism', icon: 'GlassWater', description: 'Efeito vidro com blur', preview: 'glass', category: 'estilo' },
  { id: 'soft-ui', label: 'UI Suave', labelEn: 'Soft UI', icon: 'Cloud', description: 'Neumorphism leve e suave', preview: 'soft', category: 'estilo' },
  { id: 'editorial', label: 'Editorial', labelEn: 'Editorial', icon: 'BookOpen', description: 'Foco em tipografia e conteúdo', preview: 'editorial', category: 'estilo', premium: true },
  { id: 'gaming', label: 'Gamer', labelEn: 'Gaming', icon: 'Gamepad2', description: 'Estilo gamer com cores vibrantes', preview: 'gaming', category: 'estilo' },
  { id: 'ecommerce', label: 'E-commerce Premium', labelEn: 'E-commerce Premium', icon: 'ShoppingBag', description: 'Loja virtual com design premium', preview: 'ecommerce', category: 'estilo' },
  { id: 'saas', label: 'SaaS Moderno', labelEn: 'Modern SaaS', icon: 'Layout', description: 'Layout moderno para SaaS', preview: 'saas', category: 'estilo' },
  { id: 'awwwards', label: 'Estilo Awwwards', labelEn: 'Awwwards Style', icon: 'Trophy', description: 'Design premiado e inovador', preview: 'awwwards', category: 'estilo', premium: true },
  { id: 'cinematic', label: 'Cinematic', labelEn: 'Cinematic', icon: 'Clapperboard', description: 'Composição de filme: luz dramática, profundidade e movimento de câmera', preview: 'cinematic', category: 'estilo', premium: true },
  { id: 'magazine', label: 'Magazine', labelEn: 'Magazine', icon: 'Newspaper', description: 'Grid editorial de revista com hierarquia tipográfica forte', preview: 'magazine', category: 'estilo', premium: true },
  { id: 'poster', label: 'Poster', labelEn: 'Poster', icon: 'Image', description: 'Peças gráficas tipo pôster com tipografia gigante e composição ousada', preview: 'poster', category: 'estilo', premium: true },
  { id: 'brutalist', label: 'Brutalist', labelEn: 'Brutalist', icon: 'Landmark', description: 'Web bruta moderna: forte, direta e sem frescuras', preview: 'brutalist', category: 'estilo', premium: true },
  { id: 'swiss-design', label: 'Swiss Design', labelEn: 'Swiss Design', icon: 'Ruler', description: 'Grid rígido, tipografia objetiva e precisão suíça', preview: 'swiss', category: 'estilo', premium: true },
  { id: 'luxury-editorial', label: 'Luxury Editorial', labelEn: 'Luxury Editorial', icon: 'Diamond', description: 'Editorial de luxo com artesanato tipográfico e acabamento impecável', preview: 'luxury-editorial', category: 'estilo', premium: true },
  { id: 'bento-premium', label: 'Bento Premium', labelEn: 'Bento Premium', icon: 'LayoutGrid', description: 'Grid bento organizado com cards elegantes e espaçamento generoso', preview: 'bento', category: 'estilo', premium: true },
  { id: 'storytelling', label: 'Storytelling', labelEn: 'Storytelling', icon: 'ScrollText', description: 'Narrativa em scroll que conta uma história seção a seção', preview: 'storytelling', category: 'estilo', premium: true },
  { id: 'light-mode', label: 'Claro', labelEn: 'Light', icon: 'Sun', description: 'Tema claro e arejado', preview: 'light', category: 'tema' },
  { id: 'dark-mode', label: 'Escuro', labelEn: 'Dark', icon: 'Moon', description: 'Tema escuro elegante', preview: 'dark', category: 'tema' },
  { id: 'auto-theme', label: 'Auto (sistema)', labelEn: 'Auto (system)', icon: 'Monitor', description: 'Acompanha preferências do sistema', preview: 'auto', category: 'tema' },
];

export const PLATFORMS: PlatformOption[] = [
  { id: 'lovable', label: 'Lovable', icon: 'Heart', url: 'https://lovable.dev', description: 'Interfaces completas com foco em design e rapidez', color: '#A855F7', focus: 'UI/UX premium, design visual, componentes visuais, menos foco em arquitetura' },
  { id: 'bolt', label: 'Bolt.new', icon: 'Zap', url: 'https://bolt.new', description: 'Aplicações full-stack rápidas', color: '#F59E0B', focus: 'Full-stack, banco de dados, autenticação, deploy, API routes' },
  { id: 'v0', label: 'v0', icon: 'Triangle', url: 'https://v0.dev', description: 'Geração de componentes React/Next.js com Shadcn/UI', color: '#000000', focus: 'Componentes Shadcn/UI, Tailwind CSS, React, Framer Motion, layouts reutilizáveis' },
  { id: 'cursor', label: 'Cursor', icon: 'Terminal', url: 'https://cursor.sh', description: 'Projetos completos e arquitetura de código', color: '#06B6D4', focus: 'Código completo, arquitetura de pastas, componentização, tipagem, SEO, performance, design premium' },
  { id: 'claude-code', label: 'Claude Code', icon: 'Bot', url: 'https://claude.ai', description: 'Código detalhado e bem estruturado', color: '#D946EF', focus: 'Explicações detalhadas, código organizado, componentes reutilizáveis, arquitetura limpa' },
  { id: 'replit', label: 'Replit', icon: 'Code2', url: 'https://replit.com', description: 'Desenvolvimento online e prototipagem', color: '#22C55E', focus: 'Prototipagem rápida, projeto simples, dependências claras, execução online' },
  { id: 'opencode', label: 'OpenCode', icon: 'Globe', url: 'https://github.com/opencode', description: 'Agente de código open source', color: '#10B981', focus: 'Código aberto, arquitetura modular, boas práticas, contribuição社区' },
  { id: 'windsurf', label: 'Windsurf', icon: 'Wind', url: 'https://windsurf.com', description: 'IDE com IA focada em desenvolvimento', color: '#3B82F6', focus: 'Fluxo de trabalho contínuo, refatoração, sugestões de código, produtividade' },
  { id: 'copilot', label: 'GitHub Copilot', icon: 'Code2', url: 'https://github.com/features/copilot', description: 'Assistência dentro do VS Code', color: '#6366F1', focus: 'Autocomplete inteligente, snippets, testes, documentação inline' },
];

export const LANGUAGES: LanguageOption[] = [
  { id: 'pt', label: 'Português', flag: '🇧🇷', nativeName: 'Português' },
  { id: 'en', label: 'English', flag: '🇺🇸', nativeName: 'English' },
  { id: 'es', label: 'Español', flag: '🇪🇸', nativeName: 'Español' },
  { id: 'fr', label: 'Français', flag: '🇫🇷', nativeName: 'Français' },
  { id: 'de', label: 'Deutsch', flag: '🇩🇪', nativeName: 'Deutsch' },
  { id: 'it', label: 'Italiano', flag: '🇮🇹', nativeName: 'Italiano' },
];

export const ANIMATIONS_LIST: AnimationOption[] = [
  { id: 'scroll-reveal', label: 'Scroll Reveal', description: 'Elementos aparecem ao rolar', category: 'entrada' },
  { id: 'fade-in', label: 'Fade In', description: 'Fade suave na entrada', category: 'entrada' },
  { id: 'slide-in', label: 'Slide In', description: 'Deslizar para dentro', category: 'entrada' },
  { id: 'zoom-in', label: 'Zoom In', description: 'Zoom suave na entrada', category: 'entrada' },
  { id: 'stagger-children', label: 'Stagger Children', description: 'Animações em cascata', category: 'entrada' },
  { id: 'hover-effects', label: 'Hover Effects', description: 'Animações ao passar o mouse', category: 'interacao' },
  { id: 'micro-interactions', label: 'Microinterações', description: 'Pequenas animações de feedback', category: 'interacao' },
  { id: 'cursor-glow', label: 'Cursor Glow', description: 'Rastro brilhante no cursor', category: 'interacao', premium: true },
  { id: 'magnetic-buttons', label: 'Magnetic Buttons', description: 'Botões que seguem o cursor', category: 'interacao', premium: true },
  { id: 'ripple-effect', label: 'Ripple Effect', description: 'Efeito ripple ao clicar', category: 'interacao', premium: true },
  { id: 'tilt-3d', label: 'Tilt 3D Cards', description: 'Cards com efeito 3D', category: 'interacao', premium: true },
  { id: 'parallax', label: 'Parallax', description: 'Efeito de profundidade ao scroll', category: 'scroll' },
  { id: 'infinite-scroll', label: 'Infinite Scroll', description: 'Scroll infinito com carregamento', category: 'scroll', premium: true },
  { id: 'marquee', label: 'Infinite Marquee', description: 'Rolagem infinita de conteúdo', category: 'scroll', premium: true },
  { id: 'scroll-progress', label: 'Scroll Progress Bar', description: 'Barra de progresso do scroll', category: 'scroll', premium: true },
  { id: 'smooth-scroll', label: 'Smooth Scroll (Lenis)', description: 'Scroll suave e fluido', category: 'scroll', premium: true },
  { id: 'sticky-sections', label: 'Sticky Sections', description: 'Seções que ficam fixas', category: 'scroll', premium: true },
  { id: 'page-transitions', label: 'Page Transitions', description: 'Transições suaves entre páginas', category: 'navegacao' },
  { id: 'loading-skeletons', label: 'Loading Skeleton', description: 'Skeleton loading screens', category: 'navegacao' },
  { id: 'loading-spinner', label: 'Loading Spinner', description: 'Spinner animado', category: 'navegacao', premium: true },
  { id: 'typing-effect', label: 'Typing Effect', description: 'Efeito de digitação automática', category: 'texto' },
  { id: 'count-up', label: 'Counter', description: 'Animação de contagem numérica', category: 'texto', premium: true },
  { id: 'text-reveal', label: 'Text Reveal', description: 'Revelação de texto animada', category: 'texto', premium: true },
  { id: 'gradient-text', label: 'Gradient Text Animation', description: 'Texto com gradiente animado', category: 'texto', premium: true },
  { id: 'glitch-effect', label: 'Glitch Effect', description: 'Efeito de falha digital', category: 'efeitos', premium: true },
  { id: 'morphing', label: 'Morphing', description: 'Transições morph entre elementos', category: 'efeitos', premium: true },
  { id: 'glass-glow', label: 'Glass Glow', description: 'Efeito glass com brilho', category: 'efeitos', premium: true },
  { id: 'animated-gradient', label: 'Animated Gradient', description: 'Gradientes animados', category: 'efeitos', premium: true },
  { id: 'floating-elements', label: 'Floating Elements', description: 'Elementos flutuantes', category: 'efeitos', premium: true },
  { id: 'blob-animation', label: 'Blob Animation', description: 'Formas blob animadas', category: 'efeitos', premium: true },
  { id: 'background-particles', label: 'Background Particles', description: 'Partículas no fundo', category: 'efeitos', premium: true },
  { id: 'mesh-gradient', label: 'Mesh Gradient Animation', description: 'Gradiente mesh animado', category: 'efeitos', premium: true },
  { id: 'hero-animation', label: 'Hero Animation', description: 'Animação de entrada do hero', category: 'entrada' },
  { id: 'glass-hover', label: 'Glass Hover', description: 'Efeito vidro no hover', category: 'interacao' },
  { id: 'card-lift', label: 'Card Lift', description: 'Cards que elevam no hover', category: 'interacao' },
  { id: 'cta-pulse', label: 'CTA Pulse', description: 'Pulso sutil no botão principal', category: 'interacao' },
  { id: 'faq-animation', label: 'FAQ Animation', description: 'Acordeão animado do FAQ', category: 'interacao' },
  { id: 'gallery-hover', label: 'Gallery Hover', description: 'Efeitos no hover da galeria', category: 'interacao' },
  { id: 'loading-animation', label: 'Loading', description: 'Tela de loading estilizada', category: 'navegacao' },
  { id: 'mouse-trail', label: 'Mouse Trail', description: 'Rastro de partículas no cursor', category: 'interacao', premium: true },
  { id: 'sticky-scroll', label: 'Sticky Scroll', description: 'Seções com scroll fixo criativo', category: 'scroll', premium: true },
  { id: 'bento-animation', label: 'Bento Animation', description: 'Grid bento animado', category: 'efeitos', premium: true },
  { id: 'morphing-cards', label: 'Morphing Cards', description: 'Cards que se transformam', category: 'efeitos', premium: true },
  { id: 'svg-draw', label: 'SVG Draw', description: 'Desenho de SVGs animado', category: 'efeitos', premium: true },
  { id: 'timeline-animation', label: 'Timeline Animation', description: 'Linha do tempo animada', category: 'scroll', premium: true },
];

// Efeitos visuais premium (nível Awwwards) — selecionáveis no passo Design
export const VISUAL_EFFECTS: { id: string; label: string; description: string }[] = [
  { id: 'spotlight', label: 'Spotlight', description: 'Feixe de luz que segue o mouse no hero' },
  { id: 'glow-cursor', label: 'Glow Cursor', description: 'Brilho suave acompanha o cursor' },
  { id: 'noise-texture', label: 'Noise Texture', description: 'Textura de ruído sutil sobre o fundo' },
  { id: 'gradient-mesh', label: 'Gradient Mesh', description: 'Gradiente mesh animado no fundo' },
  { id: 'floating-shapes', label: 'Floating Shapes', description: 'Formas geométricas flutuando' },
  { id: 'magnetic-buttons', label: 'Magnetic Buttons', description: 'Botões que atraem o cursor' },
  { id: 'tilt-cards', label: 'Tilt Cards', description: 'Cards com inclinação 3D ao hover' },
  { id: 'blur-navbar', label: 'Blur Navbar', description: 'Navbar com backdrop blur ao rolar' },
  { id: 'animated-counter', label: 'Animated Counter', description: 'Contadores animados (stats)' },
  { id: 'timeline', label: 'Timeline', description: 'Linha do tempo visual animada' },
  { id: 'before-after', label: 'Before/After', description: 'Slider comparativo antes/depois' },
  { id: 'faq', label: 'FAQ', description: 'Acordeão de perguntas frequentes' },
  { id: 'infinite-marquee', label: 'Infinite Marquee', description: 'Faixa de conteúdo rolando infinito' },
  { id: 'scroll-progress', label: 'Scroll Progress', description: 'Barra de progresso do scroll' },
  { id: 'back-to-top', label: 'Back to Top', description: 'Botão flutuante de voltar ao topo' },
  { id: 'custom-cursor', label: 'Custom Cursor', description: 'Cursor customizado com mix-blend-mode' },
];

export const FONTS: FontOption[] = [
  { id: 'Inter', label: 'Inter', category: 'sans-serif', googleUrl: 'https://fonts.google.com/specimen/Inter', preview: 'Inter' },
  { id: 'Manrope', label: 'Manrope', category: 'sans-serif', googleUrl: 'https://fonts.google.com/specimen/Manrope', preview: 'Manrope' },
  { id: 'Satoshi', label: 'Satoshi', category: 'sans-serif', googleUrl: 'https://www.fontshare.com/fonts/satoshi', preview: 'Satoshi' },
  { id: 'Poppins', label: 'Poppins', category: 'sans-serif', googleUrl: 'https://fonts.google.com/specimen/Poppins', preview: 'Poppins' },
  { id: 'Plus Jakarta Sans', label: 'Plus Jakarta Sans', category: 'sans-serif', googleUrl: 'https://fonts.google.com/specimen/Plus+Jakarta+Sans', preview: 'Plus Jakarta Sans' },
  { id: 'Space Grotesk', label: 'Space Grotesk', category: 'sans-serif', googleUrl: 'https://fonts.google.com/specimen/Space+Grotesk', preview: 'Space Grotesk' },
  { id: 'Outfit', label: 'Outfit', category: 'sans-serif', googleUrl: 'https://fonts.google.com/specimen/Outfit', preview: 'Outfit' },
  { id: 'DM Sans', label: 'DM Sans', category: 'sans-serif', googleUrl: 'https://fonts.google.com/specimen/DM+Sans', preview: 'DM Sans' },
];

// Link real de importação para cada fonte (o Lovable/Bolt respeitam mais quando o prompt traz o <link>)
export const FONT_IMPORT_URLS: Record<string, string> = {
  'Inter': 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap',
  'Manrope': 'https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&display=swap',
  'Satoshi': 'https://api.fontshare.com/v2/css?f[]=satoshi@400,500,700,900&display=swap',
  'Poppins': 'https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap',
  'Plus Jakarta Sans': 'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap',
  'Space Grotesk': 'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&display=swap',
  'Outfit': 'https://fonts.googleapis.com/css2?family=Outfit:wght@400;500;600;700;800&display=swap',
  'DM Sans': 'https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800&display=swap',
};

// Paletas predefinidas — em vez de só color picker
export const PALETTES: { id: string; label: string; primary: string; secondary: string }[] = [
  { id: 'preto-dourado', label: 'Preto + Dourado', primary: '#0a0a0f', secondary: '#d4af37' },
  { id: 'preto-branco', label: 'Preto + Branco', primary: '#0a0a0f', secondary: '#fafafa' },
  { id: 'preto-vermelho', label: 'Preto + Vermelho', primary: '#0a0a0f', secondary: '#e11d48' },
  { id: 'preto-amarelo', label: 'Preto + Amarelo', primary: '#0a0a0f', secondary: '#facc15' },
  { id: 'azul-escuro', label: 'Azul Escuro', primary: '#0f172a', secondary: '#38bdf8' },
  { id: 'verde-premium', label: 'Verde Premium', primary: '#052e16', secondary: '#22c55e' },
  { id: 'branco-minimalista', label: 'Branco Minimalista', primary: '#ffffff', secondary: '#18181b' },
  { id: 'personalizada', label: 'Personalizada', primary: '', secondary: '' },
];

// Modos de Inteligência IA — mudam completamente as instruções do prompt
export const AI_MODES: { id: string; label: string; emoji: string; description: string; instructions: string }[] = [
  {
    id: 'conversao',
    label: 'Conversão Máxima',
    emoji: '🎯',
    description: 'Site feito para vender: CTAs em destaque, prova social e zero atrito',
    instructions: 'FOCO EM CONVERSÃO: coloque o CTA principal acima da dobra e repetido no meio/final. Use gatilhos de urgência e escassez quando fizer sentido. Prova social forte (depoimentos, números, avaliações) logo após o hero. Formulários curtos com poucos campos. Botões com texto de benefício ("Agendar meu horário" em vez de "Enviar"). Faça o caminho até a conversão ter no máximo 2 cliques.',
  },
  {
    id: 'visual-premium',
    label: 'Visual Premium',
    emoji: '💎',
    description: 'Estética de luxo: muito espaço, tipografia grande e fotografia impecável',
    instructions: 'ESTÉTICA PREMIUM: muito espaço em branco, hierarquia tipográfica ousada (títulos grandes, escalas contrastantes), fotografia de alta qualidade com tratamento consistente, paleta restrita e sofisticada, detalhes de acabamento (linhas finas, cantos levemente arredondados, micro-animações sutis). Menos é mais — cada elemento com propósito claro. Sensação de marca cara e consolidada.',
  },
  {
    id: 'agencia',
    label: 'Agência',
    emoji: '🏢',
    description: 'Portfólio, cases, processos e resultados — como agência premiada',
    instructions: 'PENSAMENTO DE AGÊNCIA: estrutura com cases/portfólio, processo de trabalho em etapas, resultados mensuráveis, depoimentos de clientes, equipe e diferenciais. Linguagem direta e profissional. CTA de orçamento/contato em destaque. Seções de serviços bem detalhadas com escopo. Números e métricas visíveis.',
  },
  {
    id: 'awwwards',
    label: 'Awwwards',
    emoji: '🏆',
    description: 'Padrão de site premiado: motion design e grids assimétricos',
    instructions: 'PADRÃO AWWWARDS: experimentação visual ousada, grids assimétricos (60/40, elementos que atravessam colunas), motion design refinado com easing customizado, micro-interações em tudo que é clicável, typography como elemento visual principal, scroll criativo (mas nunca scroll-hijacking), imagens em composições inesperadas. Cada seção deve surpreender. Nada de padrões de template.',
  },
  {
    id: 'ultra-criativo',
    label: 'Ultra Criativo',
    emoji: '🚀',
    description: 'Quebra regras: layouts inesperados e storytelling visual',
    instructions: 'ULTRA CRIATIVO: quebre convenções de layout com coragem — seções sobrepostas, elementos fora do grid, marquee com frases grandes, transições entre seções com identidade própria, storytelling visual guiando o scroll, experimentação de cor e forma. O site deve parecer um editorial de design de ponta. Mantenha legibilidade e performance — criatividade nunca pode quebrar a usabilidade.',
  },
];

// Contexto inteligente por nicho — adiciona conhecimento específico ao prompt
export const NICHE_CONTEXT: Record<string, string> = {
  fitness: 'Contexto: negócio de fitness/treinamento. Destaque planos e mensalidades, avaliação física, horários de aulas, estrutura (aparelhos, estúdio), treinadores e depoimentos de alunos. Prova social com resultados e antes/depois funciona muito bem.',
  beauty: 'Contexto: negócio de beleza/cuidados. Destaque serviços com preços, portfólio de trabalhos (fotos reais), agendamento online, equipe e produtos usados. Fotos de antes/depois e da estrutura são essenciais para gerar confiança.',
  health: 'Contexto: negócio de saúde. Transmita confiança e autoridade: credenciais da equipe, especialidades, horários de atendimento, convênios aceitos, agendamento online e diferenciais de atendimento. Tom acolhedor e profissional.',
  'real-estate': 'Contexto: negócio imobiliário. Destaque imóveis em destaque, busca/filtros, bairros atendidos, avaliações de clientes, equipe de corretores e canais de contato rápidos (WhatsApp). Tour virtual e fotos profissionais valorizam muito.',
  food: 'Contexto: negócio de alimentação. Destaque cardápio, reservas e delivery, avaliações, galeria gastronômica (fotos que dão água na boca), localização e horário de funcionamento. Pratos em destaque e diferenciais (ingredientes, receitas autorais).',
  fashion: 'Contexto: loja de moda. Destaque coleções, categorias de produtos, fotos de modelos com os produtos, tamanhos disponíveis, política de troca, frete e formas de pagamento. Visual aspiracional com tratamento consistente das fotos.',
  ecommerce: 'Contexto: e-commerce. Destaque catálogo de produtos, busca e filtros, carrinho, checkout simplificado, avaliações de clientes, frete/prazo de entrega, garantias e políticas. Otimização de conversão é prioridade.',
  law: 'Contexto: escritório jurídico. Transmita autoridade e confiança: áreas de atuação, equipe com OAB, resultados obtidos, depoimentos, artigos jurídicos e consulta/contato fácil. Tom sóbrio, sóbrio e formal.',
  finance: 'Contexto: serviços financeiros/contábeis. Destaque serviços, especialidades, segurança e credibilidade, equipe, depoimentos e planos. Tom profissional com foco em confiança (números, certificações, casos).',
  marketing: 'Contexto: agência de marketing. Destaque serviços (tráfego, social, branding), cases com resultados, processo de trabalho, equipe e depoimentos. Prova social com métricas e números de clientes.',
  photography: 'Contexto: portfólio. O site É o portfólio: galeria em destaque com filtros por categoria, trabalhos em tela cheia, depoimentos de clientes, serviços e valores, contato direto. Visual limpo que deixa as fotos brilharem.',
  saas: 'Contexto: SaaS/software. Destaque o produto com preview/hero animado, funcionalidades, planos e preços, integrações, FAQ, depoimentos e trial/CTA forte. Linguagem técnica mas acessível.',
  tech: 'Contexto: empresa de tecnologia. Destaque soluções/serviços, stack, cases, time, contato comercial e diferenciais. Tom moderno, direto e inovador.',
  travel: 'Contexto: turismo/hotelaria. Destaque acomodações/roteiros, galeria de fotos de alta qualidade, avaliações de hóspedes/clientes, reservas online, localização com mapa e diferenciais (café da manhã, piscina, etc).',
  education: 'Contexto: educação. Destaque cursos/programas, metodologia, professores, depoimentos de alunos, matrícula e FAQ. Prova social forte (alunos formados, resultados).',
  automotive: 'Contexto: serviços automotivos. Destaque serviços com preços, antes/depois (fotos de resultados), pacotes e orçamento online, agendamento e depoimentos. Confiança no trabalho e garantia.',
  pets: 'Contexto: pet shop/pet care. Destaque produtos e serviços (banho e tosa, veterinário), fotos de pets felizes, planos de assinatura, agendamento e localização. Tom acolhedor e divertido.',
  eventos: 'Contexto: eventos. Destaque tipos de evento atendidos, galeria de fotos reais, pacotes e orçamento, depoimentos e disponibilidade de agenda.',
};

// 20 nichos principais — mostrados primeiro no passo 1
export const NICHES_PRIMARY: string[] = [
  'Barbearia', 'Salão de Beleza', 'Academia', 'Clínica Médica', 'Clínica Odontológica',
  'Restaurante', 'Pizzaria', 'Hamburgueria', 'Cafeteria', 'Imobiliária',
  'Advocacia', 'Contabilidade', 'Pet Shop', 'Lava Jato', 'E-commerce',
  'Agência de Marketing', 'Portfólio', 'Psicologia', 'Nutrição', 'Clínica de Estética',
];

// Frases de impacto sugeridas por nicho — preenchem a headline automaticamente
export const HEADLINES_BY_NICHE: Record<string, string[]> = {
  'Barbearia': ['Corte que muda sua vida', 'Onde estilo vira tradição', 'Mais que um corte, uma atitude', 'Seu visual, nossa arte'],
  'Salão de Beleza': ['Realce sua beleza natural', 'Onde você brilha todos os dias', 'Beleza que transforma seu dia'],
  'Academia': ['Transforme seu corpo, mude sua vida', 'Sua melhor versão começa aqui', 'Força, foco e resultado'],
  'Clínica Médica': ['Sua saúde em boas mãos', 'Cuidado que você merece', 'Saúde e bem-estar para toda a família'],
  'Clínica Odontológica': ['Sorria com confiança', 'Seu sorriso, nossa missão', 'Saúde bucal que transforma'],
  'Psicologia': ['Sua mente merece cuidado', 'O primeiro passo para o bem-estar', 'Escuta acolhedora para sua jornada'],
  'Nutrição': ['Coma bem, viva melhor', 'Nutrição que transforma hábitos', 'Sua saúde começa no prato'],
  'Imobiliária': ['Encontre o lugar perfeito para viver', 'Seu novo lar começa aqui', 'O imóvel dos seus sonhos, perto de você'],
  'Restaurante': ['Uma experiência gastronômica inesquecível', 'Sabor que encanta', 'A arte de cozinhar, o prazer de servir'],
  'Pizzaria': ['A melhor pizza da cidade, na sua porta', 'Sabor que incanta sua vida', 'Massa artesanal, paixão em cada fatia'],
  'Hamburgueria': ['O verdadeiro sabor do artesanal', 'Hambúrguer como tem que ser', 'Paixão em forma de hambúrguer'],
  'Cafeteria': ['O melhor café da cidade', 'Seu momento perfeito começa aqui', 'Aroma que conquista'],
  'Loja de Roupas': ['Vista seu estilo', 'Moda que expressa quem você é', 'Tendências que combinam com você'],
  'Loja de Calçados': ['Passos que fazem a diferença', 'Conforto e estilo para você', 'Calce a sua melhor versão'],
  'E-commerce': ['Tudo o que você precisa, em um só lugar', 'Compre fácil, receba rápido', 'Ofertas que valem a pena'],
  'Advocacia': ['Justiça ao seu alcance', 'Defendendo seus direitos com excelência', 'Segurança jurídica para suas decisões'],
  'Contabilidade': ['Seus números em boas mãos', 'Contabilidade que simplifica sua vida', 'Crescimento com segurança fiscal'],
  'Agência de Marketing': ['Sua marca, no lugar certo', 'Resultados que vendem', 'Estratégia que move seu negócio'],
  'Portfólio': ['Histórias em cada clique', 'Imagens que falam por si', 'Capturando momentos que importam'],
  'Hotel': ['Sua estadia perfeita começa aqui', 'Conforto e sofisticação para você', 'Bem-vindo ao seu refúgio'],
  'Turismo': ['Explore o mundo com a gente', 'Sua próxima aventura começa aqui', 'Viagens inesquecíveis ao seu alcance'],
  'Pet Shop': ['Amor em forma de cuidado', 'Seu pet merece o melhor', 'Cuidado e carinho para seu melhor amigo'],
  'Lava Jato': ['Seu carro como novo', 'Brilho que impressiona', 'Cuidado completo para seu veículo'],
  'Oficina Mecânica': ['Seu carro em boas mãos', 'Confiança e segurança para dirigir', 'Mecânica honesta e eficiente'],
  'Auto Center': ['Cuidado total para o seu veículo', 'Tecnologia e confiança automotiva', 'Seu carro, nossa prioridade'],
  'Concessionária': ['O carro dos seus sonhos está aqui', 'Novos caminhos começam hoje', 'Direção com confiança'],
  'Startup': ['Inovação que transforma', 'O futuro começa aqui', 'Tecnologia para crescer'],
  'Empresa de Tecnologia': ['Tecnologia que impulsiona seu negócio', 'Soluções inovadoras para o seu sucesso', 'O futuro da sua empresa'],
  'SaaS': ['Sua solução em um só lugar', 'Tecnologia que simplifica', 'O poder da automação ao seu alcance'],
  'Escola': ['Educação que transforma futuros', 'Aprender é uma aventura', 'Formando cidadãos do amanhã'],
  'Curso Online': ['Aprenda no seu ritmo', 'Seu futuro começa hoje', 'Conhecimento sem fronteiras'],
  'Padaria': ['Sabor de casa, frescor de todo dia', 'O pão quentinho que você ama', 'Tradição e sabor em cada fornada'],
  'Sorveteria': ['O sabor que derrete seu coração', 'Momentos doces, memórias felizes', 'Gelado, cremoso e irresistível'],
  'Açaí': ['Energia e sabor em cada colherada', 'O açaí mais cremoso da cidade', 'Saudável, gelado e delicioso'],
  'Mercado': ['Tudo fresquinho, perto de você', 'Qualidade e economia no mesmo lugar', 'Do mercado pra sua mesa'],
  'Corretora de Seguros': ['Proteja o que importa', 'Sua tranquilidade começa aqui', 'Segurança para o seu futuro'],
  'Incorporadora': ['Onde seus sonhos ganham endereço', 'Projetos que transformam cidades', 'Viva em um lugar extraordinário'],
  'Condomínio': ['Viver bem, todos os dias', 'Seu refúgio no coração da cidade', 'Estrutura completa para sua família'],
  'Arquiteto': ['Projetos que contam histórias', 'Espaços que inspiram', 'Arquitetura com alma'],
  'Decoração': ['Transforme sua casa em um lar', 'Ambientes que refletem você', 'Design que abraça'],
  'Clínica de Estética': ['Realce sua beleza natural', 'Cuidados que renovam', 'Sua melhor versão, visível'],
  default: ['Sua melhor escolha começa aqui', 'Excelência que você pode confiar', 'Feito especialmente para você'],
};

export const STRUCTURES: StructureOption[] = [
  { id: 'navbar-hero', label: 'Navbar + Hero', icon: 'LayoutDashboard', description: 'Topo com navegação e banner principal', category: 'principais' },
  { id: 'sobre', label: 'Sobre', icon: 'Info', description: 'Seção sobre a empresa', category: 'principais' },
  { id: 'diferenciais', label: 'Diferenciais', icon: 'Star', description: 'Pontos fortes e vantagens competitivas', category: 'principais' },
  { id: 'servicos', label: 'Serviços', icon: 'Briefcase', description: 'Cards de serviços oferecidos', category: 'principais' },
  { id: 'produtos', label: 'Produtos', icon: 'Package', description: 'Catálogo de produtos', category: 'principais' },
  { id: 'como-funciona', label: 'Como Funciona', icon: 'Rocket', description: 'Passo a passo do processo', category: 'principais' },
  { id: 'galeria', label: 'Galeria', icon: 'Images', description: 'Galeria de fotos e vídeos', category: 'conteudo' },
  { id: 'portfolio', label: 'Portfólio', icon: 'Image', description: 'Portfólio visual', category: 'conteudo' },
  { id: 'projetos', label: 'Projetos', icon: 'FolderOpen', description: 'Galeria de projetos realizados', category: 'conteudo' },
  { id: 'videos', label: 'Vídeos', icon: 'Film', description: 'Seção de vídeos', category: 'conteudo' },
  { id: 'equipe', label: 'Equipe', icon: 'Users', description: 'Apresentação da equipe', category: 'credibilidade' },
  { id: 'clientes', label: 'Clientes', icon: 'Handshake', description: 'Logos e cases de clientes', category: 'credibilidade' },
  { id: 'depoimentos', label: 'Depoimentos', icon: 'MessageSquare', description: 'Depoimentos de clientes', category: 'credibilidade' },
  { id: 'estatisticas', label: 'Estatísticas', icon: 'BarChart3', description: 'Números e métricas', category: 'credibilidade' },
  { id: 'parceiros', label: 'Parceiros', icon: 'Heart', description: 'Logos de parceiros', category: 'credibilidade' },
  { id: 'precos', label: 'Preços', icon: 'DollarSign', description: 'Tabela de preços e planos', category: 'comercial' },
  { id: 'promocoes', label: 'Promoções', icon: 'Gift', description: 'Ofertas e promoções', category: 'comercial' },
  { id: 'agendamento', label: 'Agendamento', icon: 'Calendar', description: 'Agendamento de serviços', category: 'comercial' },
  { id: 'contato', label: 'Contato', icon: 'Mail', description: 'Formulário de contato', category: 'comercial' },
  { id: 'cta-final', label: 'CTA Final', icon: 'Target', description: 'Chamada para ação final', category: 'comercial' },
  { id: 'faq', label: 'FAQ', icon: 'HelpCircle', description: 'Perguntas frequentes', category: 'informacao' },
  { id: 'blog', label: 'Blog', icon: 'FileText', description: 'Seção de artigos e blog', category: 'informacao' },
  { id: 'localizacao', label: 'Localização', icon: 'MapPin', description: 'Mapa e localização', category: 'informacao' },
  { id: 'area-cliente', label: 'Área do Cliente', icon: 'UserCircle', description: 'Login e área restrita', category: 'sistema' },
  { id: 'login', label: 'Login', icon: 'LogIn', description: 'Página de login', category: 'sistema' },
  { id: 'dashboard', label: 'Dashboard', icon: 'LayoutDashboard', description: 'Painel administrativo', category: 'sistema' },
  { id: 'footer', label: 'Footer', icon: 'ArrowDown', description: 'Rodapé completo', category: 'principais' },
];

export const FUNCTIONALITIES: FunctionalityOption[] = [
  { id: 'auth', label: 'Login/Cadastro', icon: 'LogIn', category: 'usuarios', complexity: 'medium' },
  { id: 'profile', label: 'Perfil do Usuário', icon: 'User', category: 'usuarios', complexity: 'medium' },
  { id: 'password-recovery', label: 'Recuperação de Senha', icon: 'KeyRound', category: 'usuarios', complexity: 'medium' },
  { id: 'social-login', label: 'Login Google/GitHub', icon: 'Globe', category: 'usuarios', complexity: 'medium' },
  { id: 'dashboard', label: 'Dashboard', icon: 'LayoutDashboard', category: 'painel', complexity: 'high' },
  { id: 'analytics', label: 'Analytics', icon: 'BarChart3', category: 'painel', complexity: 'high' },
  { id: 'notifications', label: 'Notificações', icon: 'Bell', category: 'painel', complexity: 'medium' },
  { id: 'search', label: 'Busca Inteligente', icon: 'Search', category: 'pesquisa', complexity: 'high' },
  { id: 'filters', label: 'Filtros', icon: 'Filter', category: 'pesquisa', complexity: 'medium' },
  { id: 'sorting', label: 'Ordenação', icon: 'ArrowUpDown', category: 'pesquisa', complexity: 'low' },
  { id: 'upload', label: 'Upload', icon: 'Upload', category: 'arquivos', complexity: 'medium' },
  { id: 'download', label: 'Download', icon: 'Download', category: 'arquivos', complexity: 'low' },
  { id: 'export', label: 'Exportação', icon: 'FileDown', category: 'arquivos', complexity: 'medium' },
  { id: 'chat', label: 'Chat', icon: 'MessageCircle', category: 'comunicacao', complexity: 'high' },
  { id: 'comments', label: 'Comentários', icon: 'MessageSquare', category: 'comunicacao', complexity: 'medium' },
  { id: 'newsletter', label: 'Newsletter', icon: 'Mail', category: 'comunicacao', complexity: 'medium' },
  { id: 'social-share', label: 'Compartilhamento', icon: 'Share2', category: 'comunicacao', complexity: 'low' },
  { id: 'dark-mode', label: 'Tema Dark/Light', icon: 'Moon', category: 'sistema', complexity: 'low' },
  { id: 'multilingual', label: 'Multi Idioma', icon: 'Languages', category: 'sistema', complexity: 'high' },
  { id: 'api', label: 'API', icon: 'Code', category: 'sistema', complexity: 'high' },
  { id: 'caching', label: 'Cache Inteligente', icon: 'Database', category: 'sistema', complexity: 'medium' },
  { id: 'payment', label: 'Pagamentos', icon: 'CreditCard', category: 'comercial', complexity: 'high' },
  { id: 'booking', label: 'Agendamento', icon: 'Calendar', category: 'comercial', complexity: 'high' },
];

export const OBJECTIVES: ObjectiveOption[] = [
  { id: 'landing-page', label: 'Landing Page', icon: 'Rocket', description: 'Página de conversão focada em vendas', category: 'sites' },
  { id: 'site-institucional', label: 'Site Institucional', icon: 'Building2', description: 'Site completo para empresa', category: 'sites' },
  { id: 'ecommerce', label: 'Loja Virtual', icon: 'ShoppingCart', description: 'E-commerce completo', category: 'sites' },
  { id: 'portfolio', label: 'Portfólio', icon: 'Images', description: 'Portfólio profissional', category: 'sites' },
  { id: 'blog', label: 'Blog', icon: 'FileText', description: 'Blog com artigos e conteúdo', category: 'sites' },
  { id: 'documentacao', label: 'Documentação', icon: 'BookOpen', description: 'Documentação técnica', category: 'sites' },
  { id: 'central-ajuda', label: 'Central de Ajuda', icon: 'HelpCircle', description: 'FAQ e suporte', category: 'sites' },
  { id: 'sistema-web', label: 'Sistema Web', icon: 'Monitor', description: 'Sistema administrativo completo', category: 'aplicacoes' },
  { id: 'dashboard', label: 'Dashboard', icon: 'BarChart3', description: 'Painel de indicadores e métricas', category: 'aplicacoes' },
  { id: 'sistema-admin', label: 'Sistema Administrativo', icon: 'Settings', description: 'Painel admin completo', category: 'aplicacoes' },
  { id: 'pwa', label: 'Aplicativo Web (PWA)', icon: 'Smartphone', description: 'App web progressivo', category: 'aplicacoes' },
  { id: 'crm', label: 'CRM', icon: 'Users', description: 'Gestão de relacionamento com clientes', category: 'aplicacoes' },
  { id: 'erp', label: 'ERP', icon: 'Building', description: 'Gestão empresarial integrada', category: 'aplicacoes' },
  { id: 'agendamento', label: 'Sistema de Agendamento', icon: 'Calendar', description: 'Agendamento de serviços', category: 'aplicacoes' },
  { id: 'reservas', label: 'Sistema de Reservas', icon: 'Ticket', description: 'Reservas e bilhetes', category: 'aplicacoes' },
  { id: 'marketplace', label: 'Marketplace', icon: 'Store', description: 'Plataforma multi-vendedor', category: 'negocios' },
  { id: 'area-membros', label: 'Área de Membros', icon: 'Lock', description: 'Conteúdo exclusivo por assinatura', category: 'negocios' },
  { id: 'saas', label: 'Plataforma SaaS', icon: 'Cloud', description: 'Software como serviço', category: 'negocios' },
  { id: 'lms', label: 'Plataforma de Cursos', icon: 'GraduationCap', description: 'LMS e ensino online', category: 'negocios' },
  { id: 'restaurante', label: 'Sistema para Restaurantes', icon: 'UtensilsCrossed', description: 'Pedidos e gestão', category: 'negocios' },
  { id: 'hotel', label: 'Sistema para Hotéis', icon: 'Hotel', description: 'Reservas e gestão hoteleira', category: 'negocios' },
  { id: 'clinica', label: 'Sistema para Clínicas', icon: 'Stethoscope', description: 'Prontuário e agendamento', category: 'negocios' },
  { id: 'pagina-captura', label: 'Página de Captura', icon: 'Mail', description: 'Captura de leads', category: 'marketing' },
  { id: 'pagina-lancamento', label: 'Página de Lançamento', icon: 'Megaphone', description: 'Lançamento de produto', category: 'marketing' },
  { id: 'pagina-vendas', label: 'Página de Vendas', icon: 'DollarSign', description: 'Página de vendas', category: 'marketing' },
  { id: 'pagina-evento', label: 'Página de Evento', icon: 'PartyPopper', description: 'Evento e convidativos', category: 'marketing' },
  { id: 'custom', label: 'Personalizado', icon: 'Pencil', description: 'Descreva seu projeto', category: 'custom' },
];

export const CONTRACT_TYPES: ContractTypeOption[] = [
  { id: 'site', label: 'Desenvolvimento de Site', icon: 'Globe', description: 'Criação de sites profissionais', defaultClauses: ['escopo', 'prazo', 'valor', 'pagamento', 'entrega', 'revisao', 'rescisao', 'confidencialidade', 'propriedade', 'garantia', 'foro'] },
  { id: 'landing-page', label: 'Landing Page', icon: 'Layout', description: 'Páginas de conversão', defaultClauses: ['escopo', 'prazo', 'valor', 'pagamento', 'entrega', 'revisao', 'rescisao'] },
  { id: 'sistema-web', label: 'Sistema Web', icon: 'Monitor', description: 'Sistemas web completos', defaultClauses: ['escopo', 'prazo', 'valor', 'pagamento', 'entrega', 'escopo', 'rescisao', 'confidencialidade', 'propriedade', 'garantia'] },
  { id: 'dashboard', label: 'Dashboard', icon: 'BarChart3', description: 'Painéis de métricas', defaultClauses: ['escopo', 'prazo', 'valor', 'pagamento', 'entrega', 'revisao'] },
  { id: 'aplicativo', label: 'Aplicativo', icon: 'Smartphone', description: 'Apps mobile', defaultClauses: ['escopo', 'prazo', 'valor', 'pagamento', 'entrega', 'revisao', 'rescisao', 'propriedade', 'garantia'] },
  { id: 'loja-virtual', label: 'Loja Virtual', icon: 'ShoppingCart', description: 'E-commerce', defaultClauses: ['escopo', 'prazo', 'valor', 'pagamento', 'entrega', 'escopo', 'rescisao', 'confidencialidade', 'garantia'] },
  { id: 'saas', label: 'SaaS', icon: 'Cloud', description: 'Software como serviço', defaultClauses: ['escopo', 'prazo', 'valor', 'pagamento', 'entrega', 'escopo', 'rescisao', 'confidencialidade', 'propriedade', 'garantia', 'foro'] },
  { id: 'manutencao', label: 'Manutenção', icon: 'Wrench', description: 'Manutenção contínua', defaultClauses: ['escopo', 'prazo', 'valor', 'pagamento', 'escopo', 'rescisao'] },
  { id: 'hospedagem', label: 'Hospedagem', icon: 'Database', description: 'Serviços de hospedagem', defaultClauses: ['escopo', 'prazo', 'valor', 'pagamento', 'escopo', 'rescisao', 'garantia'] },
  { id: 'consultoria', label: 'Consultoria', icon: 'Lightbulb', description: 'Consultoria técnica', defaultClauses: ['escopo', 'prazo', 'valor', 'pagamento', 'confidencialidade', 'rescisao'] },
  { id: 'seo', label: 'SEO', icon: 'Search', description: 'Otimização para buscadores', defaultClauses: ['escopo', 'prazo', 'valor', 'pagamento', 'entrega', 'rescisao', 'confidencialidade'] },
  { id: 'marketing-digital', label: 'Marketing Digital', icon: 'Megaphone', description: 'Gestão de marketing', defaultClauses: ['escopo', 'prazo', 'valor', 'pagamento', 'confidencialidade', 'rescisao'] },
];

export const CLAUSES: ClauseOption[] = [
  { id: 'escopo', label: 'Escopo do Projeto', icon: 'FileText', description: 'Detalhamento completo do escopo', required: true },
  { id: 'prazo', label: 'Prazo de Entrega', icon: 'Calendar', description: 'Cronograma e datas', required: true },
  { id: 'valor', label: 'Valor e Forma de Pagamento', icon: 'DollarSign', description: 'Condições financeiras', required: true },
  { id: 'pagamento', label: 'Condições de Pagamento', icon: 'CreditCard', description: 'Detalhamento do pagamento', required: true },
  { id: 'entrega', label: 'Entrega e Aceitação', icon: 'CheckCircle2', description: 'Critérios de entrega', required: false },
  { id: 'revisao', label: 'Revisões e Alterações', icon: 'RefreshCw', description: 'Quantidade de revisões', required: false },
  { id: 'rescisao', label: 'Rescisão', icon: 'XCircle', description: 'Condições de rescisão', required: true },
  { id: 'confidencialidade', label: 'Confidencialidade', icon: 'Lock', description: 'NDA e privacidade', required: false },
  { id: 'propriedade', label: 'Direitos Autorais', icon: 'Copyright', description: 'Propriedade intelectual', required: false },
  { id: 'garantia', label: 'Garantia', icon: 'Shield', description: 'Garantia dos serviços', required: false },
  { id: 'foro', label: 'Foro', icon: 'Scale', description: 'Foro de eleição', required: true },
];

export const PAYMENT_METHODS: PaymentMethodOption[] = [
  { id: 'pix', label: 'PIX', icon: 'QrCode', description: 'Pagamento instantâneo' },
  { id: 'cartao', label: 'Cartão de Crédito', icon: 'CreditCard', description: 'Pagamento com cartão' },
  { id: 'boleto', label: 'Boleto', icon: 'FileText', description: 'Boleto bancário' },
  { id: 'transferencia', label: 'Transferência', icon: 'ArrowLeftRight', description: 'Transferência bancária' },
];

export const SIDEBAR_NAV: NavItem[] = [
  { id: 'dashboard', label: 'Dashboard', icon: 'LayoutDashboard', path: '/dashboard' },
  { id: 'find-stores', label: 'Encontrar Lojas', icon: 'Store', path: '/dashboard/find-stores' },
  { id: 'new-prompt', label: 'Novo Prompt', icon: 'Sparkles', path: '/dashboard/wizard' },
  { id: 'history', label: 'Histórico', icon: 'History', path: '/dashboard/history' },
  { id: 'script', label: 'Script', icon: 'PhoneCall', path: '/dashboard/script' },
  { id: 'favorites', label: 'Favoritos', icon: 'Heart', path: '/dashboard/favorites' },
  { id: 'projects', label: 'Projetos', icon: 'FolderKanban', path: '/dashboard/projects' },
  { id: 'contracts', label: 'Gerador de Contratos', icon: 'FileSignature', path: '/dashboard/contracts' },
  { id: 'proposals', label: 'Propostas Comerciais', icon: 'FileText', path: '/dashboard/proposals' },
  { id: 'budgets', label: 'Orçamentos', icon: 'DollarSign', path: '/dashboard/budgets' },
  { id: 'briefings', label: 'Briefings', icon: 'ClipboardList', path: '/dashboard/briefings' },
  { id: 'premium', label: 'Premium', icon: 'Crown', path: '/dashboard/plans' },
  { id: 'profile', label: 'Perfil', icon: 'User', path: '/dashboard/profile' },
  { id: 'settings', label: 'Configurações', icon: 'Settings', path: '/dashboard/settings' },
];

export interface SidebarGroup {
  label: string;
  icon: string;
  items: NavItem[];
}

export const SIDEBAR_GROUPS: SidebarGroup[] = [
  {
    label: 'Criar',
    icon: 'Zap',
    items: [
      { id: 'new-prompt', label: 'Novo Prompt', icon: 'Sparkles', path: '/dashboard/wizard', highlight: true },
      { id: 'contracts', label: 'Contratos', icon: 'FileSignature', path: '/dashboard/contracts' },
      { id: 'proposals', label: 'Propostas', icon: 'FileText', path: '/dashboard/proposals' },
      { id: 'budgets', label: 'Orçamentos', icon: 'DollarSign', path: '/dashboard/budgets' },
      { id: 'briefings', label: 'Briefings', icon: 'ClipboardList', path: '/dashboard/briefings' },
      { id: 'script', label: 'Script de Vendas', icon: 'PhoneCall', path: '/dashboard/script' },
    ],
  },
  {
    label: 'Gerenciar',
    icon: 'FolderKanban',
    items: [
      { id: 'dashboard', label: 'Dashboard', icon: 'LayoutDashboard', path: '/dashboard' },
      { id: 'projects', label: 'Projetos', icon: 'FolderKanban', path: '/dashboard/projects' },
      { id: 'history', label: 'Histórico', icon: 'History', path: '/dashboard/history' },
      { id: 'favorites', label: 'Favoritos', icon: 'Heart', path: '/dashboard/favorites' },
      { id: 'find-stores', label: 'Encontrar Lojas', icon: 'Store', path: '/dashboard/find-stores' },
    ],
  },
  {
    label: 'Conta',
    icon: 'User',
    items: [
      { id: 'premium', label: 'Premium', icon: 'Crown', path: '/dashboard/plans', badge: 'PRO' },
      { id: 'profile', label: 'Perfil', icon: 'User', path: '/dashboard/profile' },
      { id: 'settings', label: 'Configurações', icon: 'Settings', path: '/dashboard/settings' },
    ],
  },
];

export const LANDING_NAV_ITEMS = [
  { label: 'Início', href: '#hero' },
  { label: 'Recursos', href: '#features' },
  { label: 'Como Funciona', href: '#how-it-works' },
  { label: 'Planos', href: '#pricing' },
  { label: 'FAQ', href: '#faq' },
  { label: 'Contato', href: '#contact' },
];

export const LOGOS = [
  { name: 'React', icon: '⚛️', color: '#61DAFB' },
  { name: 'Next.js', icon: '▲', color: '#FFFFFF' },
  { name: 'TypeScript', icon: '📘', color: '#3178C6' },
  { name: 'Tailwind CSS', icon: '🎨', color: '#06B6D4' },
  { name: 'Node.js', icon: '🟢', color: '#339933' },
  { name: 'Supabase', icon: '⚡', color: '#3ECF8E' },
  { name: 'PostgreSQL', icon: '🐘', color: '#4169E1' },
  { name: 'Framer Motion', icon: '🎬', color: '#0055FF' },
  { name: 'NVIDIA AI', icon: '🧠', color: '#76B900' },
];

export const BENEFITS = [
  { title: 'Economize horas', description: 'Crie prompts completos em minutos, não em horas. Automatize o processo criativo.', icon: 'Clock' },
  { title: 'Prompts extremamente completos', description: 'Prompts detalhados com estrutura, tecnologias, animações e boas práticas.', icon: 'FileCheck' },
  { title: 'Compatível com várias plataformas', description: 'Prompts otimizados para Lovable, Bolt.new, v0, Cursor e outras.', icon: 'MonitorSmartphone' },
  { title: 'Organize projetos', description: 'Gerencie prompts, contratos e documentos em projetos organizados.', icon: 'FolderTree' },
  { title: 'Contratos profissionais', description: 'Gere contratos personalizados com cláusulas jurídicas completas.', icon: 'FileSignature' },
  { title: 'Tudo em um só lugar', description: 'Prompts, contratos, propostas, briefings e orçamentos integrados.', icon: 'LayoutGrid' },
];

export const HOW_IT_WORKS = [
  { step: 1, title: 'Escolha o nicho', description: 'Selecione entre mais de 30 nichos ou crie um personalizado.', icon: 'Layers' },
  { step: 2, title: 'Responda perguntas', description: 'Nosso wizard inteligente guia você por cada detalhe do projeto.', icon: 'HelpCircle' },
  { step: 3, title: 'IA cria o prompt', description: 'NVIDIA AI gera um prompt completo e profissional automaticamente.', icon: 'Brain' },
  { step: 4, title: 'Copie e utilize', description: 'Use o prompt em qualquer plataforma de IA e veja seu projeto ganhar vida.', icon: 'CopyCheck' },
];

export const TESTIMONIALS = [
  { id: '1', name: 'Carlos Silva', role: 'CEO, Agência DigitalWeb', avatar: 'CS', content: 'PromptForge revolucionou nossa agência. Reduzimos o tempo de criação de briefings de 3 horas para 15 minutos.', rating: 5 },
  { id: '2', name: 'Juliana Costa', role: 'Freelancer', avatar: 'JC', content: 'Como freelancer, otimizar meu tempo é essencial. A plataforma me ajuda a entregar propostas profissionais em minutos.', rating: 5 },
  { id: '3', name: 'Rafael Oliveira', role: 'CTO, TechStart', avatar: 'RO', content: 'A qualidade dos prompts gerados pela IA da NVIDIA é impressionante. Detalhes que realmente fazem diferença no resultado final.', rating: 5 },
  { id: '4', name: 'Ana Beatriz', role: 'Designer Lead, UXLab', avatar: 'AB', content: 'Uso para criar briefings completos para minha equipe. A integração com Lovable e v0 é simplesmente fantástica.', rating: 5 },
  { id: '5', name: 'Pedro Santos', role: 'Desenvolvedor Full Stack', avatar: 'PS', content: 'Os prompts gerados já vêm com stack tecnológica, arquitetura e boas práticas. É como ter um arquiteto de software ajudando.', rating: 5 },
  { id: '6', name: 'Marina Lima', role: 'Head de Marketing, GrupoXYZ', avatar: 'ML', content: 'Geramos landing pages completas em dias, não semanas. O ROI da ferramenta se paga no primeiro projeto.', rating: 5 },
];

export const FAQ_ITEMS = [
  { question: 'O que é a PromptForge AI?', answer: 'A PromptForge AI é uma plataforma SaaS que utiliza inteligência artificial (NVIDIA AI) para gerar prompts profissionais, contratos, propostas comerciais, orçamentos e briefings para criação de sites, sistemas web, aplicativos e muito mais.' },
  { question: 'Como funciona o gerador de prompts?', answer: 'Nosso Wizard Inteligente guia você por 15 etapas: escolha do nicho, dados da empresa, objetivo, público-alvo, estilo visual, cores, tipografia, animações, estrutura, funcionalidades, tecnologias, plataforma de destino e briefing. No final, a IA da NVIDIA gera um prompt completo e otimizado.' },
  { question: 'Preciso de conhecimento técnico?', answer: 'Não. A plataforma foi projetada para ser intuitiva. Basta responder as perguntas do wizard e a IA cuida do resto. O resultado é um prompt profissional mesmo para quem não tem experiência técnica.' },
  { question: 'Quais plataformas são suportadas?', answer: 'Atualmente suportamos Lovable, Bolt.new, v0, Cursor, Claude Code e Replit. A IA adapta automaticamente o prompt para cada plataforma.' },
  { question: 'Posso gerar prompts em outros idiomas?', answer: 'Sim! Oferecemos geração em Português, Inglês, Espanhol, Francês, Alemão e Italiano.' },
  { question: 'Os contratos gerados têm validade jurídica?', answer: 'Nossos contratos seguem modelos profissionais e incluem cláusulas comuns do mercado. Recomendamos sempre a revisão por um advogado antes da assinatura.' },
  { question: 'Como funciona o plano gratuito?', answer: 'Não existe plano grátis com geração de prompts. Sem assinatura, o acesso é limitado ao dashboard — para gerar prompts, contratos e propostas é preciso assinar o Starter (R$ 29,90/mês) ou o Pro (R$ 47/mês).' },
  { question: 'Quais formas de pagamento são aceitas?', answer: 'Aceitamos PIX, Cartão de Crédito (todas as bandeiras), Boleto Bancário e Transferência Bancária.' },
  { question: 'Posso mudar de plano depois?', answer: 'Sim! Você pode fazer upgrade ou downgrade do seu plano a qualquer momento. O valor é ajustado proporcionalmente.' },
  { question: 'Meus dados estão seguros?', answer: 'Sim. Utilizamos criptografia de ponta a ponta, autenticação segura, proteção contra SQL Injection, XSS e CSRF. Seguimos a LGPD.' },
];

export const ANIMATION_STAGES = [
  { text: 'npx promptforge --analyze', duration: 800 },
  { text: '  ✔ Analisando requisitos do projeto...', duration: 1200 },
  { text: 'npx promptforge --generate-palette', duration: 800 },
  { text: '  ✔ Gerando identidade visual...', duration: 1200 },
  { text: 'npx promptforge --build-components', duration: 800 },
  { text: '  ✔ Compilando componentes...', duration: 1200 },
  { text: 'npx promptforge --optimize', duration: 800 },
  { text: '  ✔ Otimizando prompt...', duration: 1200 },
  { text: 'npx promptforge --export', duration: 800 },
  { text: '  ✔ Prompt gerado com sucesso!', duration: 1000 },
];

export const DASHBOARD_DEFAULT_STATS = {
  totalProjects: 0,
  totalPrompts: 0,
  totalContracts: 0,
  totalProposals: 0,
  promptsThisMonth: 0,
  contractsThisMonth: 0,
  revenueThisMonth: 0,
  activeClients: 0,
};

export const MOCK_STATS = {
  totalProjects: 12,
  totalPrompts: 48,
  totalContracts: 15,
  totalProposals: 8,
  promptsThisMonth: 23,
  contractsThisMonth: 7,
  revenueThisMonth: 28450,
  activeClients: 9,
};

export const COLOR_PALETTES = [
  { name: 'Roxo Tech', colors: ['#A855F7', '#7C3AED', '#D946EF', '#1E1B4B', '#FFFFFF'] },
  { name: 'Verde Nature', colors: ['#10B981', '#059669', '#34D399', '#064E3B', '#FFFFFF'] },
  { name: 'Azul Corporate', colors: ['#3B82F6', '#2563EB', '#60A5FA', '#1E3A5F', '#FFFFFF'] },
  { name: 'Vermelho Power', colors: ['#EF4444', '#DC2626', '#F87171', '#7F1D1D', '#FFFFFF'] },
  { name: 'Laranja Fire', colors: ['#F97316', '#EA580C', '#FB923C', '#7C2D12', '#FFFFFF'] },
  { name: 'Rosa Pink', colors: ['#EC4899', '#DB2777', '#F472B6', '#831843', '#FFFFFF'] },
  { name: 'Ciano Fresh', colors: ['#06B6D4', '#0891B2', '#22D3EE', '#164E63', '#FFFFFF'] },
  { name: 'Amarelo Sun', colors: ['#EAB308', '#CA8A04', '#FDE047', '#713F12', '#FFFFFF'] },
  { name: 'Cinza Elegance', colors: ['#6B7280', '#4B5563', '#9CA3AF', '#111827', '#FFFFFF'] },
  { name: 'Dark Premium', colors: ['#A855F7', '#D946EF', '#1F2937', '#050505', '#FFFFFF'] },
];

// ── Seções recomendadas por categoria de nicho ──
// Usado quando o usuário não escolhe a estrutura manualmente: o briefing
// já sai com as seções certas para o nicho (em vez de genéricas).
export const NICHE_STRUCTURES: Record<string, string[]> = {
  fitness: ['navbar-hero', 'sobre', 'diferenciais', 'precos', 'agendamento', 'equipe', 'galeria', 'depoimentos', 'contato', 'cta-final', 'footer'],
  beauty: ['navbar-hero', 'sobre', 'servicos', 'galeria', 'precos', 'agendamento', 'depoimentos', 'localizacao', 'contato', 'cta-final', 'footer'],
  health: ['navbar-hero', 'sobre', 'servicos', 'equipe', 'diferenciais', 'depoimentos', 'agendamento', 'localizacao', 'faq', 'contato', 'cta-final', 'footer'],
  'real-estate': ['navbar-hero', 'sobre', 'projetos', 'diferenciais', 'equipe', 'depoimentos', 'localizacao', 'contato', 'cta-final', 'footer'],
  food: ['navbar-hero', 'sobre', 'galeria', 'promocoes', 'depoimentos', 'localizacao', 'contato', 'faq', 'footer'],
  fashion: ['navbar-hero', 'sobre', 'produtos', 'galeria', 'promocoes', 'depoimentos', 'localizacao', 'contato', 'footer'],
  ecommerce: ['navbar-hero', 'produtos', 'promocoes', 'depoimentos', 'faq', 'contato', 'footer'],
  law: ['navbar-hero', 'sobre', 'servicos', 'equipe', 'diferenciais', 'blog', 'faq', 'contato', 'cta-final', 'footer'],
  finance: ['navbar-hero', 'sobre', 'servicos', 'diferenciais', 'estatisticas', 'blog', 'faq', 'contato', 'cta-final', 'footer'],
  marketing: ['navbar-hero', 'sobre', 'servicos', 'projetos', 'clientes', 'depoimentos', 'blog', 'contato', 'cta-final', 'footer'],
  photography: ['navbar-hero', 'sobre', 'portfolio', 'galeria', 'depoimentos', 'precos', 'contato', 'cta-final', 'footer'],
  saas: ['navbar-hero', 'sobre', 'servicos', 'como-funciona', 'precos', 'depoimentos', 'faq', 'blog', 'contato', 'cta-final', 'footer'],
  tech: ['navbar-hero', 'sobre', 'servicos', 'como-funciona', 'projetos', 'clientes', 'blog', 'contato', 'cta-final', 'footer'],
  travel: ['navbar-hero', 'sobre', 'servicos', 'galeria', 'depoimentos', 'precos', 'blog', 'localizacao', 'contato', 'footer'],
  education: ['navbar-hero', 'sobre', 'servicos', 'equipe', 'como-funciona', 'depoimentos', 'precos', 'faq', 'contato', 'cta-final', 'footer'],
  automotive: ['navbar-hero', 'sobre', 'servicos', 'diferenciais', 'galeria', 'agendamento', 'depoimentos', 'localizacao', 'contato', 'cta-final', 'footer'],
  pet: ['navbar-hero', 'sobre', 'servicos', 'galeria', 'diferenciais', 'depoimentos', 'agendamento', 'localizacao', 'contato', 'footer'],
  events: ['navbar-hero', 'sobre', 'servicos', 'galeria', 'depoimentos', 'precos', 'agendamento', 'contato', 'cta-final', 'footer'],
};

export const DEFAULT_STRUCTURES = ['navbar-hero', 'sobre', 'servicos', 'diferenciais', 'contato', 'cta-final', 'footer'];

// ── CTA principal ──
// A ação de conversão que o site deve priorizar (vira destaque no hero).
export const CTA_OPTIONS = [
  { id: 'whatsapp', label: 'Chamar no WhatsApp', emoji: '💬' },
  { id: 'agendar', label: 'Agendar / Reservar', emoji: '📅' },
  { id: 'comprar', label: 'Comprar / Assinar', emoji: '🛒' },
  { id: 'contato', label: 'Formulário de Contato', emoji: '✉️' },
  { id: 'ligar', label: 'Ligar', emoji: '📞' },
];