import type {
  Niche, StyleOption, PlatformOption, LanguageOption, AnimationOption,
  FontOption, StructureOption, FunctionalityOption, ObjectiveOption,
  ContractTypeOption, ClauseOption, PaymentMethodOption, Plan, NavItem,
  WizardStepConfig, TechnologyOption
} from '../types';

export const PLANS: Plan[] = [
  {
    id: 'starter', name: 'Starter', price: 29.90, currency: 'BRL', period: 'monthly',
    features: [
      '100 prompts/mês', '20 contratos/mês', '20 nichos', 'Histórico completo',
      'Favoritos', 'Projetos', 'Exportação TXT', 'Exportação Markdown',
      'Português e Inglês', 'Suporte por Email', 'Atualizações constantes',
    ],
    highlighted: false, color: '#8B5CF6', icon: 'Rocket',
    promptLimit: 100, contractLimit: 20, projectLimit: 5, teamMembers: 1,
    analytics: false, prioritySupport: false,
  },
  {
    id: 'pro', name: 'Pro', price: 47.00, currency: 'BRL', period: 'monthly',
    features: [
      'Prompts ilimitados', 'Contratos ilimitados', 'Projetos ilimitados',
      'Histórico ilimitado', 'Favoritos ilimitados', 'Mais de 100 nichos',
      'Mais estilos e animações', 'Biblioteca Premium', 'Exportação PDF',
      'Exportação DOCX', 'Upload PDF/DOCX', 'IA analisa Briefings',
      'IA melhora prompts', 'IA corrige prompts', 'IA otimiza prompts',
      'IA gera versões alternativas', 'Modelos Premium', 'Contratos Premium',
      'Propostas Premium', 'Orçamentos Premium', 'Briefings Premium',
      'SEO Avançado', 'UX/UI Premium', 'Suporte Prioritário', 'Novidades antecipadas',
    ],
    highlighted: true, color: '#A855F7', icon: 'Star',
    promptLimit: Infinity, contractLimit: Infinity, projectLimit: Infinity, teamMembers: 1,
    analytics: true, prioritySupport: true,
  },
];

export const WIZARD_STEPS: WizardStepConfig[] = [
  { id: 1, title: 'Nicho', description: 'Escolha o nicho do projeto', icon: 'Layers', component: 'NicheStep' },
  { id: 2, title: 'Empresa', description: 'Dados da empresa', icon: 'Building2', component: 'CompanyStep' },
  { id: 3, title: 'Objetivo', description: 'Tipo de projeto', icon: 'Target', component: 'ObjectiveStep' },
  { id: 4, title: 'Público', description: 'Público-alvo', icon: 'Users', component: 'AudienceStep' },
  { id: 5, title: 'Estilo', description: 'Estilo visual', icon: 'Palette', component: 'StyleStep' },
  { id: 6, title: 'Cores', description: 'Paleta de cores', icon: 'Droplets', component: 'ColorsStep' },
  { id: 7, title: 'Tipografia', description: 'Fontes do projeto', icon: 'TextCursorInput', component: 'FontStep' },
  { id: 8, title: 'Animações', description: 'Efeitos e transições', icon: 'Sparkles', component: 'AnimationsStep' },
  { id: 9, title: 'Estrutura', description: 'Seções do site', icon: 'Layout', component: 'StructureStep' },
  { id: 10, title: 'Funcionalidades', description: 'Recursos do sistema', icon: 'Settings2', component: 'FeaturesStep' },
  { id: 11, title: 'Tecnologias', description: 'Stack tecnológica', icon: 'Code2', component: 'TechStep' },
  { id: 12, title: 'Plataforma', description: 'Ferramenta de destino', icon: 'Monitor', component: 'PlatformStep' },
  { id: 13, title: 'Briefing', description: 'Detalhes adicionais', icon: 'FileText', component: 'BriefingStep' },
  { id: 14, title: 'Revisão', description: 'Revise suas escolhas', icon: 'CheckCircle2', component: 'ReviewStep' },
  { id: 15, title: 'Gerar', description: 'Gerar prompt completo', icon: 'Zap', component: 'GenerateStep' },
];

export const NICHES: Niche[] = [
  { id: 'fitness', label: 'Academia', labelEn: 'Gym', icon: 'Dumbbell', emoji: '💪', description: 'Academias e centros de treinamento', color: '#EF4444' },
  { id: 'beauty', label: 'Barbearia', labelEn: 'Barbershop', icon: 'Scissors', emoji: '💈', description: 'Barbearias e cuidados masculinos', color: '#F97316' },
  { id: 'beauty', label: 'Salão de Beleza', labelEn: 'Beauty Salon', icon: 'Sparkles', emoji: '💇‍♀️', description: 'Salões e estética', color: '#EC4899' },
  { id: 'health', label: 'Clínica Médica', labelEn: 'Medical Clinic', icon: 'Stethoscope', emoji: '🏥', description: 'Consultórios e clínicas', color: '#10B981' },
  { id: 'health', label: 'Clínica Odontológica', labelEn: 'Dental Clinic', icon: 'Tooth', emoji: '🦷', description: 'Consultórios odontológicos', color: '#06B6D4' },
  { id: 'health', label: 'Psicologia', labelEn: 'Psychology', icon: 'Brain', emoji: '🧠', description: 'Profissionais de saúde mental', color: '#8B5CF6' },
  { id: 'health', label: 'Nutrição', labelEn: 'Nutrition', icon: 'Apple', emoji: '🥗', description: 'Nutricionistas e dietistas', color: '#22C55E' },
  { id: 'real-estate', label: 'Imobiliária', labelEn: 'Real Estate', icon: 'Building', emoji: '🏠', description: 'Corretoras e imobiliárias', color: '#3B82F6' },
  { id: 'food', label: 'Restaurante', labelEn: 'Restaurant', icon: 'UtensilsCrossed', emoji: '🍽️', description: 'Restaurantes e gastronomia', color: '#F59E0B' },
  { id: 'food', label: 'Pizzaria', labelEn: 'Pizzeria', icon: 'Pizza', emoji: '🍕', description: 'Pizzarias e delivery', color: '#EF4444' },
  { id: 'food', label: 'Hamburgueria', labelEn: 'Burger Shop', icon: 'Beef', emoji: '🍔', description: 'Hamburguerias artesanais', color: '#92400E' },
  { id: 'food', label: 'Cafeteria', labelEn: 'Coffee Shop', icon: 'Coffee', emoji: '☕', description: 'Cafeterias e confeitarias', color: '#78350F' },
  { id: 'fashion', label: 'Loja de Roupas', labelEn: 'Clothing Store', icon: 'Shirt', emoji: '👕', description: 'Moda e vestuário', color: '#EC4899' },
  { id: 'fashion', label: 'Loja de Calçados', labelEn: 'Shoe Store', icon: 'Footprints', emoji: '👟', description: 'Calçados e acessórios', color: '#8B5CF6' },
  { id: 'ecommerce', label: 'E-commerce', labelEn: 'E-commerce', icon: 'ShoppingCart', emoji: '🛒', description: 'Lojas virtuais completas', color: '#F97316' },
  { id: 'law', label: 'Advocacia', labelEn: 'Law Firm', icon: 'Scale', emoji: '⚖️', description: 'Escritórios de advocacia', color: '#1E40AF' },
  { id: 'finance', label: 'Contabilidade', labelEn: 'Accounting', icon: 'Calculator', emoji: '📊', description: 'Escritórios contábeis', color: '#059669' },
  { id: 'finance', label: 'Corretora de Seguros', labelEn: 'Insurance Broker', icon: 'Shield', emoji: '🛡️', description: 'Corretoras e seguros', color: '#2563EB' },
  { id: 'marketing', label: 'Agência de Marketing', labelEn: 'Marketing Agency', icon: 'Megaphone', emoji: '📢', description: 'Agências de marketing digital', color: '#D946EF' },
  { id: 'photography', label: 'Portfólio', labelEn: 'Portfolio', icon: 'Image', emoji: '📸', description: 'Portfólios profissionais', color: '#A855F7' },
  { id: 'saas', label: 'SaaS', labelEn: 'SaaS', icon: 'Cloud', emoji: '☁️', description: 'Software como serviço', color: '#06B6D4', premium: true },
  { id: 'tech', label: 'Startup', labelEn: 'Startup', icon: 'Rocket', emoji: '🚀', description: 'Startups inovadoras', color: '#F59E0B', premium: true },
  { id: 'tech', label: 'Empresa de Tecnologia', labelEn: 'Tech Company', icon: 'Monitor', emoji: '💻', description: 'Empresas de TI', color: '#3B82F6', premium: true },
  { id: 'travel', label: 'Hotel', labelEn: 'Hotel', icon: 'Hotel', emoji: '🏨', description: 'Hotéis e hospedagem', color: '#8B5CF6', premium: true },
  { id: 'travel', label: 'Turismo', labelEn: 'Tourism', icon: 'Globe', emoji: '✈️', description: 'Agências de turismo', color: '#0EA5E9', premium: true },
  { id: 'education', label: 'Escola', labelEn: 'School', icon: 'GraduationCap', emoji: '🏫', description: 'Escolas e colégios', color: '#10B981', premium: true },
  { id: 'education', label: 'Curso Online', labelEn: 'Online Course', icon: 'Video', emoji: '🎓', description: 'Cursos e plataformas EAD', color: '#D946EF', premium: true },
  { id: 'automotive', label: 'Oficina Mecânica', labelEn: 'Auto Repair', icon: 'Wrench', emoji: '🔧', description: 'Oficinas e reparos', color: '#6B7280', premium: true },
  { id: 'automotive', label: 'Auto Center', labelEn: 'Auto Center', icon: 'Car', emoji: '🚗', description: 'Centros automotivos', color: '#1F2937', premium: true },
  { id: 'automotive', label: 'Concessionária', labelEn: 'Dealership', icon: 'CarFront', emoji: '🚘', description: 'Concessionárias de veículos', color: '#2563EB', premium: true },
  { id: 'real-estate', label: 'Incorporadora', labelEn: 'Real Estate Developer', icon: 'Building2', emoji: '🏗️', description: 'Incorporadoras e construtoras', color: '#DC2626', premium: true },
  { id: 'real-estate', label: 'Condomínio', labelEn: 'Condominium', icon: 'DoorOpen', emoji: '🏢', description: 'Condomínios residenciais', color: '#7C3AED', premium: true },
  { id: 'real-estate', label: 'Arquiteto', labelEn: 'Architect', icon: 'PencilRuler', emoji: '📐', description: 'Escritórios de arquitetura', color: '#F59E0B', premium: true },
  { id: 'real-estate', label: 'Decoração', labelEn: 'Interior Design', icon: 'Sofa', emoji: '🛋️', description: 'Design de interiores', color: '#EC4899', premium: true },
  { id: 'food', label: 'Padaria', labelEn: 'Bakery', icon: 'Bread', emoji: '🥖', description: 'Padarias e confeitarias', color: '#92400E', premium: true },
  { id: 'food', label: 'Sorveteria', labelEn: 'Ice Cream Shop', icon: 'IceCream', emoji: '🍦', description: 'Sorveterias e gelaterias', color: '#F472B6', premium: true },
  { id: 'food', label: 'Açaí', labelEn: 'Açaí Shop', icon: 'Fruit', emoji: '🫐', description: 'Açaí e bowls saudáveis', color: '#7C3AED', premium: true },
  { id: 'food', label: 'Mercado', labelEn: 'Grocery Store', icon: 'ShoppingBasket', emoji: '🛒', description: 'Supermercados e mercearias', color: '#22C55E', premium: true },
  { id: 'food', label: 'Adega', labelEn: 'Winery', icon: 'Wine', emoji: '🍷', description: 'Adegas e lojas de vinhos', color: '#7F1D1D', premium: true },
  { id: 'food', label: 'Churrascaria', labelEn: 'Steakhouse', icon: 'Flame', emoji: '🥩', description: 'Churrascarias e parrillas', color: '#B91C1C', premium: true },
  { id: 'food', label: 'Sushi', labelEn: 'Sushi Bar', icon: 'Fish', emoji: '🍣', description: 'Restaurantes japoneses', color: '#0F766E', premium: true },
  { id: 'food', label: 'Petiscaria', labelEn: 'Pub Food', icon: 'Beer', emoji: '🍻', description: 'Bares e petiscarias', color: '#A16207', premium: true },
  { id: 'health', label: 'Veterinário', labelEn: 'Veterinary', icon: 'Cat', emoji: '🐾', description: 'Clínicas veterinárias', color: '#0D9488', premium: true },
  { id: 'health', label: 'Fisioterapia', labelEn: 'Physical Therapy', icon: 'Bone', emoji: '🦴', description: 'Clínicas de fisioterapia', color: '#0891B2', premium: true },
  { id: 'health', label: 'Oftalmologia', labelEn: 'Ophthalmology', icon: 'Eye', emoji: '👁️', description: 'Consultórios oftalmológicos', color: '#0284C7', premium: true },
  { id: 'health', label: 'Dermatologia', labelEn: 'Dermatology', icon: 'Droplets', emoji: '🧴', description: 'Clínicas dermatológicas', color: '#DB2777', premium: true },
  { id: 'health', label: 'Fonoaudiologia', labelEn: 'Speech Therapy', icon: 'Ear', emoji: '👂', description: 'Clínicas de fonoaudiologia', color: '#7C3AED', premium: true },
  { id: 'health', label: 'Cardiologia', labelEn: 'Cardiology', icon: 'HeartPulse', emoji: '❤️', description: 'Consultórios cardiológicos', color: '#DC2626', premium: true },
  { id: 'health', label: 'Pediatria', labelEn: 'Pediatrics', icon: 'Baby', emoji: '👶', description: 'Consultórios pediátricos', color: '#0EA5E9', premium: true },
  { id: 'health', label: 'Acupuntura', labelEn: 'Acupuncture', icon: 'Needle', emoji: '🪡', description: 'Terapias orientais', color: '#10B981', premium: true },
  { id: 'beauty', label: 'Clínica de Estética', labelEn: 'Aesthetics Clinic', icon: 'Wand', emoji: '✨', description: 'Clínicas de estética avançada', color: '#EC4899', premium: true },
  { id: 'beauty', label: 'Depilação', labelEn: 'Hair Removal', icon: 'Zap', emoji: '⚡', description: 'Centros de depilação', color: '#D946EF', premium: true },
  { id: 'beauty', label: 'Tatuagem', labelEn: 'Tattoo Studio', icon: 'Pen', emoji: '🖊️', description: 'Estúdios de tatuagem', color: '#1F2937', premium: true },
  { id: 'beauty', label: 'Massoterapia', labelEn: 'Massage Therapy', icon: 'Hand', emoji: '💆', description: 'Centros de massagem', color: '#A855F7', premium: true },
  { id: 'beauty', label: 'Perfumaria', labelEn: 'Perfumery', icon: 'Flower2', emoji: '🌸', description: 'Lojas de perfumes', color: '#F472B6', premium: true },
  { id: 'fitness', label: 'CrossFit', labelEn: 'CrossFit', icon: 'Flame', emoji: '🔥', description: 'Box de CrossFit', color: '#DC2626', premium: true },
  { id: 'fitness', label: 'Pilates', labelEn: 'Pilates Studio', icon: 'Accessibility', emoji: '🧘', description: 'Estúdios de pilates', color: '#8B5CF6', premium: true },
  { id: 'fitness', label: 'Yoga', labelEn: 'Yoga Studio', icon: 'Gem', emoji: '🧘‍♀️', description: 'Estúdios de yoga', color: '#F59E0B', premium: true },
  { id: 'fitness', label: 'Esporte', labelEn: 'Sports', icon: 'Trophy', emoji: '🏆', description: 'Clubes e centros esportivos', color: '#2563EB', premium: true },
  { id: 'fashion', label: 'Joalheria', labelEn: 'Jewelry', icon: 'Gem', emoji: '💎', description: 'Joalherias e bijuterias', color: '#F59E0B', premium: true },
  { id: 'fashion', label: 'Ótica', labelEn: 'Optical Store', icon: 'Glasses', emoji: '👓', description: 'Óticas e relojoarias', color: '#0F766E', premium: true },
  { id: 'fashion', label: 'Moda Infantil', labelEn: 'Kids Fashion', icon: 'Baby', emoji: '👶', description: 'Moda para crianças', color: '#0EA5E9', premium: true },
  { id: 'fashion', label: 'Moda Fitness', labelEn: 'Activewear', icon: 'Dumbbell', emoji: '🏃', description: 'Moda esportiva', color: '#7C3AED', premium: true },
  { id: 'fashion', label: 'Moda Íntima', labelEn: 'Lingerie', icon: 'Heart', emoji: '💕', description: 'Lingerie e moda praia', color: '#DB2777', premium: true },
  { id: 'fashion', label: 'Moda Masculina', labelEn: 'Men Fashion', icon: 'Shirt', emoji: '👔', description: 'Moda masculina premium', color: '#1E3A5F', premium: true },
  { id: 'fashion', label: 'Bolsas e Acessórios', labelEn: 'Bags & Accessories', icon: 'Baggage', emoji: '👜', description: 'Lojas de acessórios', color: '#78350F', premium: true },
  { id: 'food', label: 'Marmitaria', labelEn: 'Meal Prep', icon: 'Package', emoji: '📦', description: 'Marmitas e alimentação saudável', color: '#16A34A', premium: true },
  { id: 'food', label: 'Food Truck', labelEn: 'Food Truck', icon: 'Truck', emoji: '🚚', description: 'Food trucks e trailers', color: '#EA580C', premium: true },
  { id: 'food', label: 'Doceria', labelEn: 'Candy Shop', icon: 'Candy', emoji: '🍬', description: 'Doces e sobremesas', color: '#F472B6', premium: true },
  { id: 'food', label: 'Pet Shop', labelEn: 'Pet Shop', icon: 'Dog', emoji: '🐕', description: 'Lojas de animais e pet care', color: '#F97316', premium: true },
  { id: 'food', label: 'Distribuidora', labelEn: 'Distributor', icon: 'Truck', emoji: '🚛', description: 'Distribuidoras alimentícias', color: '#475569', premium: true },
  { id: 'law', label: 'Cartório', labelEn: 'Notary', icon: 'FileText', emoji: '📜', description: 'Cartórios e tabelionatos', color: '#78350F', premium: true },
  { id: 'law', label: 'Consultoria Jurídica', labelEn: 'Legal Consulting', icon: 'BookOpen', emoji: '📚', description: 'Consultorias jurídicas', color: '#1E40AF', premium: true },
  { id: 'law', label: 'Justiça Trabalhista', labelEn: 'Labor Law', icon: 'Users', emoji: '👥', description: 'Direito trabalhista', color: '#B91C1C', premium: true },
  { id: 'finance', label: 'Fintech', labelEn: 'Fintech', icon: 'Banknote', emoji: '💰', description: 'Startups financeiras', color: '#059669', premium: true },
  { id: 'finance', label: 'Banco Digital', labelEn: 'Digital Bank', icon: 'Landmark', emoji: '🏦', description: 'Bancos e instituições financeiras', color: '#2563EB', premium: true },
  { id: 'finance', label: 'Investimentos', labelEn: 'Investments', icon: 'TrendingUp', emoji: '📈', description: 'Consultorias de investimento', color: '#16A34A', premium: true },
  { id: 'finance', label: 'Câmbio', labelEn: 'Currency Exchange', icon: 'ArrowLeftRight', emoji: '🔄', description: 'Casas de câmbio', color: '#0891B2', premium: true },
  { id: 'education', label: 'Universidade', labelEn: 'University', icon: 'GraduationCap', emoji: '🎓', description: 'Universidades e faculdades', color: '#7C3AED', premium: true },
  { id: 'education', label: 'Idiomas', labelEn: 'Language School', icon: 'Languages', emoji: '🗣️', description: 'Escolas de idiomas', color: '#06B6D4', premium: true },
  { id: 'education', label: 'Música', labelEn: 'Music School', icon: 'Music', emoji: '🎵', description: 'Escolas de música', color: '#D946EF', premium: true },
  { id: 'education', label: 'Dança', labelEn: 'Dance School', icon: 'Music4', emoji: '💃', description: 'Escolas de dança', color: '#EC4899', premium: true },
  { id: 'education', label: 'Reforço Escolar', labelEn: 'Tutoring', icon: 'BookOpenText', emoji: '📖', description: 'Aulas particulares', color: '#F59E0B', premium: true },
  { id: 'education', label: 'Curso Técnico', labelEn: 'Technical Course', icon: 'Wrench', emoji: '🔧', description: 'Cursos profissionalizantes', color: '#0891B2', premium: true },
  { id: 'education', label: 'Auto Escola', labelEn: 'Driving School', icon: 'Car', emoji: '🚗', description: 'Auto escolas e CFCs', color: '#DC2626', premium: true },
  { id: 'tech', label: 'Agência de Tecnologia', labelEn: 'Tech Agency', icon: 'Code', emoji: '💻', description: 'Agências de desenvolvimento', color: '#2563EB', premium: true },
  { id: 'tech', label: 'Game Dev', labelEn: 'Game Development', icon: 'Gamepad2', emoji: '🎮', description: 'Estúdios de games', color: '#7C3AED', premium: true },
  { id: 'tech', label: 'Cibersegurança', labelEn: 'Cybersecurity', icon: 'Shield', emoji: '🔒', description: 'Empresas de segurança digital', color: '#DC2626', premium: true },
  { id: 'tech', label: 'Inteligência Artificial', labelEn: 'Artificial Intelligence', icon: 'BrainCircuit', emoji: '🤖', description: 'Empresas de IA', color: '#A855F7', premium: true },
  { id: 'tech', label: 'Blockchain', labelEn: 'Blockchain', icon: 'Hexagon', emoji: '⛓️', description: 'Blockchain e criptomoedas', color: '#F59E0B', premium: true },
  { id: 'tech', label: 'SaaS B2B', labelEn: 'B2B SaaS', icon: 'Cloud', emoji: '☁️', description: 'SaaS para empresas', color: '#0284C7', premium: true },
  { id: 'tech', label: 'IoT', labelEn: 'IoT', icon: 'Cpu', emoji: '🔌', description: 'Internet das Coisas', color: '#0D9488', premium: true },
  { id: 'tech', label: 'Data Science', labelEn: 'Data Science', icon: 'Database', emoji: '📊', description: 'Análise e ciência de dados', color: '#8B5CF6', premium: true },
  { id: 'travel', label: 'Pousada', labelEn: 'Inn', icon: 'House', emoji: '🏡', description: 'Pousadas e chalés', color: '#0D9488', premium: true },
  { id: 'travel', label: 'Resort', labelEn: 'Resort', icon: 'Umbrella', emoji: '🏖️', description: 'Resorts all-inclusive', color: '#0EA5E9', premium: true },
  { id: 'travel', label: 'Agência de Viagem', labelEn: 'Travel Agency', icon: 'Plane', emoji: '✈️', description: 'Agências de viagens', color: '#2563EB', premium: true },
  { id: 'travel', label: 'Camping', labelEn: 'Camping', icon: 'Tent', emoji: '🏕️', description: 'Campings e glamping', color: '#16A34A', premium: true },
  { id: 'travel', label: 'Aluguel Temporada', labelEn: 'Vacation Rental', icon: 'Key', emoji: '🔑', description: 'Aluguel por temporada', color: '#F97316', premium: true },
  { id: 'marketing', label: 'Social Media', labelEn: 'Social Media Agency', icon: 'Share2', emoji: '📱', description: 'Agências de mídias sociais', color: '#EC4899', premium: true },
  { id: 'marketing', label: 'SEO', labelEn: 'SEO Agency', icon: 'Search', emoji: '🔍', description: 'Agências de SEO', color: '#059669', premium: true },
  { id: 'marketing', label: 'Growth', labelEn: 'Growth Marketing', icon: 'TrendingUp', emoji: '📈', description: 'Growth marketing', color: '#D946EF', premium: true },
  { id: 'marketing', label: 'Influencer', labelEn: 'Influencer', icon: 'Camera', emoji: '📸', description: 'Gestão de influenciadores', color: '#F59E0B', premium: true },
  { id: 'photography', label: 'Filmagem', labelEn: 'Videography', icon: 'Video', emoji: '🎥', description: 'Produtoras de vídeo', color: '#DC2626', premium: true },
  { id: 'photography', label: 'Casamentos', labelEn: 'Wedding Photography', icon: 'Heart', emoji: '💒', description: 'Fotografia de casamentos', color: '#F472B6', premium: true },
  { id: 'photography', label: 'Drone', labelEn: 'Drone Services', icon: 'Plane', emoji: '🛸', description: 'Serviços com drones', color: '#0891B2', premium: true },
  { id: 'servicos', label: 'Hotel para Pets', labelEn: 'Pet Hotel', icon: 'Dog', emoji: '🐶', description: 'Hotéis e creches para pets', color: '#F97316', premium: true },
  { id: 'servicos', label: 'Lavanderia', labelEn: 'Laundry', icon: 'Shirt', emoji: '👔', description: 'Lavanderias e tinturarias', color: '#6B7280', premium: true },
  { id: 'servicos', label: 'Segurança', labelEn: 'Security', icon: 'ShieldAlert', emoji: '🛡️', description: 'Empresas de segurança', color: '#1E3A5F', premium: true },
  { id: 'servicos', label: 'Limpeza', labelEn: 'Cleaning Services', icon: 'SprayCan', emoji: '🧹', description: 'Serviços de limpeza', color: '#0EA5E9', premium: true },
  { id: 'servicos', label: 'Jardinagem', labelEn: 'Gardening', icon: 'Leaf', emoji: '🌿', description: 'Paisagismo e jardinagem', color: '#16A34A', premium: true },
  { id: 'servicos', label: 'Dedetizadora', labelEn: 'Pest Control', icon: 'Bug', emoji: '🐛', description: 'Controle de pragas', color: '#78350F', premium: true },
  { id: 'servicos', label: 'Mudanças', labelEn: 'Moving Company', icon: 'Truck', emoji: '🚚', description: 'Empresas de mudança', color: '#2563EB', premium: true },
  { id: 'servicos', label: 'Chaveiro', labelEn: 'Locksmith', icon: 'KeyRound', emoji: '🔐', description: 'Chaveiros 24h', color: '#92400E', premium: true },
  { id: 'servicos', label: 'Borracheiro', labelEn: 'Tire Shop', icon: 'Circle', emoji: '⚙️', description: 'Borracharias e pneus', color: '#1F2937', premium: true },
  { id: 'servicos', label: 'Assistência Técnica', labelEn: 'Tech Support', icon: 'Wrench', emoji: '🔧', description: 'Assistência de eletrônicos', color: '#0891B2', premium: true },
  { id: 'servicos', label: 'Funilaria', labelEn: 'Auto Body Shop', icon: 'Car', emoji: '🚗', description: 'Funilarias e pintura', color: '#B91C1C', premium: true },
  { id: 'servicos', label: 'Instalação Elétrica', labelEn: 'Electrical Services', icon: 'Zap', emoji: '⚡', description: 'Eletricistas e instalações', color: '#F59E0B', premium: true },
  { id: 'servicos', label: 'Encanador', labelEn: 'Plumbing', icon: 'Droplets', emoji: '🔧', description: 'Serviços hidráulicos', color: '#06B6D4', premium: true },
];

export const STYLES: StyleOption[] = [
  { id: 'minimalista', label: 'Minimalista', labelEn: 'Minimalist', icon: 'CircleDot', description: 'Limpo, espaçoso e focado no conteúdo', preview: 'minimal' },
  { id: 'luxury', label: 'Apple Style', labelEn: 'Apple Style', icon: 'Apple', description: 'Premium, minimalista com tipografia impecável', preview: 'apple', premium: true },
  { id: 'luxury', label: 'Premium', labelEn: 'Premium', icon: 'Gem', description: 'Design luxuoso com detalhes sofisticados', preview: 'premium', premium: true },
  { id: 'dark-mode', label: 'Dark', labelEn: 'Dark', icon: 'Moon', description: 'Tema escuro elegante', preview: 'dark' },
  { id: 'flat-design', label: 'Light', labelEn: 'Light', icon: 'Sun', description: 'Tema claro e arejado', preview: 'light' },
  { id: 'glassmorphism', label: 'Glassmorphism', labelEn: 'Glassmorphism', icon: 'GlassWater', description: 'Efeito vidro com blur', preview: 'glass' },
  { id: 'cyberpunk', label: 'Neon', labelEn: 'Neon', icon: 'Zap', description: 'Cores vibrantes e efeitos neon', preview: 'neon' },
  { id: 'cyberpunk', label: 'Cyberpunk', labelEn: 'Cyberpunk', icon: 'Cpu', description: 'Futurista com vibe cyberpunk', preview: 'cyberpunk', premium: true },
  { id: 'gradient-rich', label: 'Futurista', labelEn: 'Futuristic', icon: 'Rocket', description: 'Design com linhas e grids futuristas', preview: 'futuristic', premium: true },
  { id: 'corporate', label: 'Corporativo', labelEn: 'Corporate', icon: 'Briefcase', description: 'Visual profissional e sóbrio', preview: 'corporate' },
  { id: 'luxury', label: 'Elegante', labelEn: 'Elegant', icon: 'Feather', description: 'Refinado com tipografia clássica', preview: 'elegant', premium: true },
  { id: 'luxury', label: 'Luxuoso', labelEn: 'Luxurious', icon: 'Crown', description: 'Alto padrão com detalhes dourados', preview: 'luxury', premium: true },
  { id: 'corporate', label: 'Tecnológico', labelEn: 'Tech', icon: 'Cpu', description: 'Moderna e tech-driven', preview: 'tech' },
  { id: 'playful', label: 'Moderno', labelEn: 'Modern', icon: 'Sparkles', description: 'Contemporâneo e versátil', preview: 'modern' },
];

export const PLATFORMS: PlatformOption[] = [
  { id: 'lovable', label: 'Lovable', icon: 'Heart', url: 'https://lovable.dev', description: 'Plataforma de criação visual com IA', color: '#A855F7' },
  { id: 'bolt', label: 'Bolt.new', icon: 'Zap', url: 'https://bolt.new', description: 'Criação de apps full-stack com IA', color: '#F59E0B' },
  { id: 'v0', label: 'v0', icon: 'Triangle', url: 'https://v0.dev', description: 'Gerador de interfaces da Vercel', color: '#000000' },
  { id: 'cursor', label: 'Cursor', icon: 'CursorArrow', url: 'https://cursor.sh', description: 'IDE com IA integrada', color: '#06B6D4' },
  { id: 'claude-code', label: 'Claude Code', icon: 'Bot', url: 'https://claude.ai', description: 'Codificação com Claude AI', color: '#D946EF' },
  { id: 'replit', label: 'Replit', icon: 'Code2', url: 'https://replit.com', description: 'IDE online colaborativa', color: '#22C55E' },
];

export const LANGUAGES: LanguageOption[] = [
  { id: 'pt', label: 'Português', flag: '🇧🇷', nativeName: 'Português' },
  { id: 'en', label: 'English', flag: '🇺🇸', nativeName: 'English' },
  { id: 'es', label: 'Español', flag: '🇪🇸', nativeName: 'Español' },
  { id: 'fr', label: 'Français', flag: '🇫🇷', nativeName: 'Français' },
  { id: 'de', label: 'Deutsch', flag: '🇩🇪', nativeName: 'Deutsch' },
  { id: 'it', label: 'Italiano', flag: '🇮🇹', nativeName: 'Italiano' },
];

export const ANIMATIONS_LIST: AnimationOption[] = [
  { id: 'scroll-reveal', label: 'Scroll Reveal', description: 'Elementos aparecem ao rolar', category: 'entrance' },
  { id: 'parallax', label: 'Parallax', description: 'Efeito de profundidade ao scroll', category: 'scroll' },
  { id: 'hover-effects', label: 'Hover Effects', description: 'Animações ao passar o mouse', category: 'interaction' },
  { id: 'page-transitions', label: 'Page Transitions', description: 'Transições suaves entre páginas', category: 'navigation' },
  { id: 'loading-skeletons', label: 'Loading Skeleton', description: 'Skeleton loading screens', category: 'feedback' },
  { id: 'micro-interactions', label: 'Microinterações', description: 'Pequenas animações de feedback', category: 'interaction' },
  { id: 'typing-effect', label: 'Typing Effect', description: 'Efeito de digitação automática', category: 'text' },
  { id: 'glitch-effect', label: 'Glitch Effect', description: 'Efeito de falha digital', category: 'text', premium: true },
  { id: 'morphing', label: 'Morphing', description: 'Transições morph entre elementos', category: 'transition', premium: true },
  { id: 'infinite-scroll', label: 'Infinite Scroll', description: 'Scroll infinito com carregamento', category: 'scroll', premium: true },
  { id: 'stagger-children', label: 'Stagger Children', description: 'Animações em cascata', category: 'entrance' },
  { id: 'cursor-trail', label: 'Cursor Glow', description: 'Rastro brilhante no cursor', category: 'interaction', premium: true },
  { id: 'count-up', label: 'Counter', description: 'Animação de contagem numérica', category: 'text', premium: true },
  { id: 'marquee', label: 'Infinite Marquee', description: 'Rolagem infinita de conteúdo', category: 'scroll', premium: true },
];

export const FONTS: FontOption[] = [
  { id: 'Inter', label: 'Inter', category: 'sans-serif', googleUrl: 'https://fonts.google.com/specimen/Inter', preview: 'Inter' },
  { id: 'Manrope', label: 'Manrope', category: 'sans-serif', googleUrl: 'https://fonts.google.com/specimen/Manrope', preview: 'Manrope' },
  { id: 'Satoshi', label: 'Satoshi', category: 'sans-serif', googleUrl: 'https://www.fontshare.com/fonts/satoshi', preview: 'Satoshi' },
  { id: 'Poppins', label: 'Poppins', category: 'sans-serif', googleUrl: 'https://fonts.google.com/specimen/Poppins', preview: 'Poppins' },
  { id: 'Plus Jakarta Sans', label: 'Plus Jakarta Sans', category: 'sans-serif', googleUrl: 'https://fonts.google.com/specimen/Plus+Jakarta+Sans', preview: 'Plus Jakarta Sans' },
  { id: 'Space Grotesk', label: 'Space Grotesk', category: 'sans-serif', googleUrl: 'https://fonts.google.com/specimen/Space+Grotesk', preview: 'Space Grotesk' },
];

export const STRUCTURES: StructureOption[] = [
  { id: 'navbar-hero', label: 'Navbar + Hero', icon: 'LayoutDashboard', description: 'Topo com navegação e banner principal' },
  { id: 'sobre', label: 'Sobre', icon: 'Info', description: 'Seção sobre a empresa' },
  { id: 'servicos', label: 'Serviços', icon: 'Briefcase', description: 'Cards de serviços oferecidos' },
  { id: 'projetos', label: 'Projetos', icon: 'FolderOpen', description: 'Galeria de projetos realizados' },
  { id: 'portfolio', label: 'Portfólio', icon: 'Image', description: 'Portfólio visual' },
  { id: 'equipe', label: 'Equipe', icon: 'Users', description: 'Apresentação da equipe' },
  { id: 'clientes', label: 'Clientes', icon: 'Handshake', description: 'Logos e cases de clientes' },
  { id: 'galeria', label: 'Galeria', icon: 'Images', description: 'Galeria de fotos e vídeos' },
  { id: 'depoimentos', label: 'Depoimentos', icon: 'MessageSquare', description: 'Depoimentos de clientes' },
  { id: 'faq', label: 'FAQ', icon: 'HelpCircle', description: 'Perguntas frequentes' },
  { id: 'precos', label: 'Preços', icon: 'DollarSign', description: 'Tabela de preços e planos' },
  { id: 'contato', label: 'Contato', icon: 'Mail', description: 'Formulário de contato' },
  { id: 'footer', label: 'Footer', icon: 'ArrowDown', description: 'Rodapé completo' },
  { id: 'cta-final', label: 'CTA Final', icon: 'Target', description: 'Chamada para ação final' },
  { id: 'blog', label: 'Blog', icon: 'FileText', description: 'Seção de artigos e blog' },
  { id: 'area-cliente', label: 'Área do Cliente', icon: 'UserCircle', description: 'Login e área restrita' },
];

export const FUNCTIONALITIES: FunctionalityOption[] = [
  { id: 'auth', label: 'Login/Cadastro', icon: 'LogIn', category: 'auth', complexity: 'medium' },
  { id: 'dark-mode', label: 'Tema Dark/Light', icon: 'Moon', category: 'ux', complexity: 'low' },
  { id: 'multilingual', label: 'Multi Idioma', icon: 'Languages', category: 'ux', complexity: 'high' },
  { id: 'dashboard', label: 'Dashboard', icon: 'LayoutDashboard', category: 'admin', complexity: 'high' },
  { id: 'search', label: 'Busca Inteligente', icon: 'Search', category: 'core', complexity: 'high' },
  { id: 'filters', label: 'Filtros', icon: 'Filter', category: 'core', complexity: 'medium' },
  { id: 'notifications', label: 'Notificações', icon: 'Bell', category: 'ux', complexity: 'medium' },
  { id: 'chat', label: 'Chat', icon: 'MessageCircle', category: 'communication', complexity: 'high' },
  { id: 'payment', label: 'Pagamentos', icon: 'CreditCard', category: 'finance', complexity: 'high' },
  { id: 'upload', label: 'Upload', icon: 'Upload', category: 'core', complexity: 'medium' },
  { id: 'download', label: 'Download', icon: 'Download', category: 'core', complexity: 'low' },
  { id: 'analytics', label: 'Analytics', icon: 'BarChart3', category: 'admin', complexity: 'high' },
  { id: 'api', label: 'API', icon: 'Api', category: 'integration', complexity: 'high' },
  { id: 'newsletter', label: 'Newsletter', icon: 'Mail', category: 'marketing', complexity: 'medium' },
  { id: 'social-share', label: 'Compartilhamento', icon: 'Share2', category: 'social', complexity: 'low' },
  { id: 'comments', label: 'Comentários', icon: 'MessageSquare', category: 'social', complexity: 'medium' },
  { id: 'booking', label: 'Agendamento', icon: 'Calendar', category: 'core', complexity: 'high' },
  { id: 'export', label: 'Exportação', icon: 'FileDown', category: 'core', complexity: 'medium' },
  { id: 'sorting', label: 'Ordenação', icon: 'ArrowUpDown', category: 'core', complexity: 'low' },
  { id: 'caching', label: 'Cache Inteligente', icon: 'Database', category: 'performance', complexity: 'medium' },
];

export const OBJECTIVES: ObjectiveOption[] = [
  { id: 'landing-page', label: 'Landing Page', icon: 'Layout', description: 'Página de conversão focada em vendas' },
  { id: 'site-institucional', label: 'Site Institucional', icon: 'Building2', description: 'Site completo para empresa' },
  { id: 'sistema-web', label: 'Sistema Web', icon: 'Monitor', description: 'Sistema administrativo completo' },
  { id: 'dashboard', label: 'Dashboard', icon: 'BarChart3', description: 'Painel de indicadores e métricas' },
  { id: 'app-mobile', label: 'Aplicativo', icon: 'Smartphone', description: 'App mobile responsivo' },
  { id: 'ecommerce', label: 'Loja Virtual', icon: 'ShoppingCart', description: 'E-commerce completo' },
  { id: 'portfolio', label: 'Portfólio', icon: 'Images', description: 'Portfólio profissional' },
  { id: 'pagina-captura', label: 'Página de Captura', icon: 'Mail', description: 'Página para captura de leads' },
  { id: 'blog', label: 'Blog', icon: 'FileText', description: 'Blog com artigos e conteúdo' },
  { id: 'marketplace', label: 'Marketplace', icon: 'Store', description: 'Plataforma multi-vendedor' },
  { id: 'area-membros', label: 'Área de Membros', icon: 'Users', description: 'Conteúdo exclusivo por assinatura' },
  { id: 'crm', label: 'CRM', icon: 'UserCheck', description: 'Gestão de relacionamento com clientes' },
  { id: 'erp', label: 'ERP', icon: 'Building', description: 'Gestão empresarial integrada' },
  { id: 'sistema-admin', label: 'Sistema Administrativo', icon: 'Settings', description: 'Painel admin completo' },
];

export const TECHNOLOGIES: TechnologyOption[] = [
  { id: 'React', label: 'React', category: 'frontend', icon: '⚛️', popular: true },
  { id: 'Next.js', label: 'Next.js', category: 'frontend', icon: '▲', popular: true },
  { id: 'Vue.js', label: 'Vue', category: 'frontend', icon: '💚', popular: false },
  { id: 'Angular', label: 'Angular', category: 'frontend', icon: '🔴', popular: false },
  { id: 'Node.js', label: 'Node.js', category: 'backend', icon: '🟢', popular: true },
  { id: 'NestJS', label: 'NestJS', category: 'backend', icon: '🏗️', popular: false },
  { id: 'Laravel', label: 'Laravel', category: 'backend', icon: '🔶', popular: false },
  { id: 'Supabase', label: 'Supabase', category: 'database', icon: '⚡', popular: true },
  { id: 'PostgreSQL', label: 'PostgreSQL', category: 'database', icon: '🐘', popular: true },
  { id: 'MySQL', label: 'MySQL', category: 'database', icon: '🐬', popular: false },
  { id: 'Firebase', label: 'Firebase', category: 'database', icon: '🔥', popular: true },
  { id: 'MongoDB', label: 'MongoDB', category: 'database', icon: '🍃', popular: true },
  { id: 'Vercel', label: 'Vercel', category: 'hosting', icon: '▲', popular: true },
  { id: 'Railway', label: 'Railway', category: 'hosting', icon: '🚂', popular: false },
  { id: 'Render', label: 'Render', category: 'hosting', icon: '🖥️', popular: false },
  { id: 'AWS', label: 'AWS', category: 'hosting', icon: '☁️', popular: true },
  { id: 'Cloudflare', label: 'Cloudflare', category: 'hosting', icon: '🌐', popular: true },
];

export const CONTRACT_TYPES: ContractTypeOption[] = [
  { id: 'site', label: 'Desenvolvimento de Site', icon: 'Globe', description: 'Criação de sites profissionais', defaultClauses: ['escopo', 'prazo', 'valor', 'pagamento', 'entrega', 'revisao', 'rescisao', 'confidencialidade', 'propriedade', 'garantia', 'foro'] },
  { id: 'landing-page', label: 'Landing Page', icon: 'Layout', description: 'Páginas de conversão', defaultClauses: ['escopo', 'prazo', 'valor', 'pagamento', 'entrega', 'revisao', 'rescisao'] },
  { id: 'sistema-web', label: 'Sistema Web', icon: 'Monitor', description: 'Sistemas web completos', defaultClauses: ['escopo', 'prazo', 'valor', 'pagamento', 'entrega', 'escopo', 'rescisao', 'confidencialidade', 'propriedade', 'garantia'] },
  { id: 'dashboard', label: 'Dashboard', icon: 'BarChart3', description: 'Painéis de métricas', defaultClauses: ['escopo', 'prazo', 'valor', 'pagamento', 'entrega', 'revisao'] },
  { id: 'aplicativo', label: 'Aplicativo', icon: 'Smartphone', description: 'Apps mobile', defaultClauses: ['escopo', 'prazo', 'valor', 'pagamento', 'entrega', 'revisao', 'rescisao', 'propriedade', 'garantia'] },
  { id: 'loja-virtual', label: 'Loja Virtual', icon: 'ShoppingCart', description: 'E-commerce', defaultClauses: ['escopo', 'prazo', 'valor', 'pagamento', 'entrega', 'escopo', 'rescisao', 'confidencialidade', 'garantia'] },
  { id: 'saas', label: 'SaaS', icon: 'Cloud', description: 'Software como serviço', defaultClauses: ['escopo', 'prazo', 'valor', 'pagamento', 'entrega', 'escopo', 'rescisao', 'confidencialidade', 'propriedade', 'garantia', 'foro'] },
  { id: 'manutencao', label: 'Manutenção', icon: 'Wrench', description: 'Manutenção contínua', defaultClauses: ['escopo', 'prazo', 'valor', 'pagamento', 'escopo', 'rescisao'] },
  { id: 'hospedagem', label: 'Hospedagem', icon: 'Database', description: 'Serviços de hospedagem', defaultClauses: ['escopo', 'prazo', 'valor', 'pagamento', 'escopo', 'rescisao', 'garantia'] },
  { id: 'consultoria', label: 'Consultoria', icon: 'Lightbulb', description: 'Consultoria técnica', defaultClauses: ['escopo', 'prazo', 'valor', 'pagamento', 'confidencialidade', 'rescisao'] },
  { id: 'seo', label: 'SEO', icon: 'Search', description: 'Otimização para buscadores', defaultClauses: ['escopo', 'prazo', 'valor', 'pagamento', 'entrega', 'rescisao', 'confidencialidade'] },
  { id: 'marketing-digital', label: 'Marketing Digital', icon: 'Megaphone', description: 'Gestão de marketing', defaultClauses: ['escopo', 'prazo', 'valor', 'pagamento', 'confidencialidade', 'rescisao'] },
];

export const CLAUSES: ClauseOption[] = [
  { id: 'escopo', label: 'Escopo do Projeto', icon: 'FileText', description: 'Detalhamento completo do escopo', required: true },
  { id: 'prazo', label: 'Prazo de Entrega', icon: 'Calendar', description: 'Cronograma e datas', required: true },
  { id: 'valor', label: 'Valor e Forma de Pagamento', icon: 'DollarSign', description: 'Condições financeiras', required: true },
  { id: 'pagamento', label: 'Condições de Pagamento', icon: 'CreditCard', description: 'Detalhamento do pagamento', required: true },
  { id: 'entrega', label: 'Entrega e Aceitação', icon: 'CheckCircle2', description: 'Critérios de entrega', required: false },
  { id: 'revisao', label: 'Revisões e Alterações', icon: 'RefreshCw', description: 'Quantidade de revisões', required: false },
  { id: 'rescisao', label: 'Rescisão', icon: 'XCircle', description: 'Condições de rescisão', required: true },
  { id: 'confidencialidade', label: 'Confidencialidade', icon: 'Lock', description: 'NDA e privacidade', required: false },
  { id: 'propriedade', label: 'Direitos Autorais', icon: 'Copyright', description: 'Propriedade intelectual', required: false },
  { id: 'garantia', label: 'Garantia', icon: 'Shield', description: 'Garantia dos serviços', required: false },
  { id: 'foro', label: 'Foro', icon: 'Scale', description: 'Foro de eleição', required: true },
];

export const PAYMENT_METHODS: PaymentMethodOption[] = [
  { id: 'pix', label: 'PIX', icon: 'QrCode', description: 'Pagamento instantâneo' },
  { id: 'cartao', label: 'Cartão de Crédito', icon: 'CreditCard', description: 'Pagamento com cartão' },
  { id: 'boleto', label: 'Boleto', icon: 'FileText', description: 'Boleto bancário' },
  { id: 'transferencia', label: 'Transferência', icon: 'ArrowLeftRight', description: 'Transferência bancária' },
];

export const SIDEBAR_NAV: NavItem[] = [
  { id: 'dashboard', label: 'Dashboard', icon: 'LayoutDashboard', path: '/dashboard' },
  { id: 'find-stores', label: 'Encontrar Lojas', icon: 'Store', path: '/dashboard/find-stores' },
  { id: 'new-prompt', label: 'Novo Prompt', icon: 'Sparkles', path: '/dashboard/wizard' },
  { id: 'history', label: 'Histórico', icon: 'History', path: '/dashboard/history' },
  { id: 'script', label: 'Script', icon: 'PhoneCall', path: '/dashboard/script' },
  { id: 'favorites', label: 'Favoritos', icon: 'Heart', path: '/dashboard/favorites' },
  { id: 'projects', label: 'Projetos', icon: 'FolderKanban', path: '/dashboard/projects' },
  { id: 'contracts', label: 'Gerador de Contratos', icon: 'FileSignature', path: '/dashboard/contracts' },
  { id: 'proposals', label: 'Propostas Comerciais', icon: 'FileText', path: '/dashboard/proposals' },
  { id: 'budgets', label: 'Orçamentos', icon: 'DollarSign', path: '/dashboard/budgets' },
  { id: 'briefings', label: 'Briefings', icon: 'ClipboardList', path: '/dashboard/briefings' },
  { id: 'premium', label: 'Premium', icon: 'Crown', path: '/dashboard/plans' },
  { id: 'profile', label: 'Perfil', icon: 'User', path: '/dashboard/profile' },
  { id: 'settings', label: 'Configurações', icon: 'Settings', path: '/dashboard/settings' },
];

export const LANDING_NAV_ITEMS = [
  { label: 'Início', href: '#hero' },
  { label: 'Recursos', href: '#features' },
  { label: 'Como Funciona', href: '#how-it-works' },
  { label: 'Planos', href: '#pricing' },
  { label: 'FAQ', href: '#faq' },
  { label: 'Contato', href: '#contact' },
];

export const LOGOS = [
  { name: 'React', icon: '⚛️', color: '#61DAFB' },
  { name: 'Next.js', icon: '▲', color: '#FFFFFF' },
  { name: 'TypeScript', icon: '📘', color: '#3178C6' },
  { name: 'Tailwind CSS', icon: '🎨', color: '#06B6D4' },
  { name: 'Node.js', icon: '🟢', color: '#339933' },
  { name: 'Supabase', icon: '⚡', color: '#3ECF8E' },
  { name: 'PostgreSQL', icon: '🐘', color: '#4169E1' },
  { name: 'Framer Motion', icon: '🎬', color: '#0055FF' },
  { name: 'NVIDIA AI', icon: '🧠', color: '#76B900' },
];

export const BENEFITS = [
  { title: 'Economize horas', description: 'Crie prompts completos em minutos, não em horas. Automatize o processo criativo.', icon: 'Clock' },
  { title: 'Prompts extremamente completos', description: 'Prompts detalhados com estrutura, tecnologias, animações e boas práticas.', icon: 'FileCheck' },
  { title: 'Compatível com várias plataformas', description: 'Prompts otimizados para Lovable, Bolt.new, v0, Cursor e outras.', icon: 'MonitorSmartphone' },
  { title: 'Organize projetos', description: 'Gerencie prompts, contratos e documentos em projetos organizados.', icon: 'FolderTree' },
  { title: 'Contratos profissionais', description: 'Gere contratos personalizados com cláusulas jurídicas completas.', icon: 'FileSignature' },
  { title: 'Tudo em um só lugar', description: 'Prompts, contratos, propostas, briefings e orçamentos integrados.', icon: 'LayoutGrid' },
];

export const HOW_IT_WORKS = [
  { step: 1, title: 'Escolha o nicho', description: 'Selecione entre mais de 30 nichos ou crie um personalizado.', icon: 'Layers' },
  { step: 2, title: 'Responda perguntas', description: 'Nosso wizard inteligente guia você por cada detalhe do projeto.', icon: 'HelpCircle' },
  { step: 3, title: 'IA cria o prompt', description: 'NVIDIA AI gera um prompt completo e profissional automaticamente.', icon: 'Brain' },
  { step: 4, title: 'Copie e utilize', description: 'Use o prompt em qualquer plataforma de IA e veja seu projeto ganhar vida.', icon: 'CopyCheck' },
];

export const TESTIMONIALS = [
  { id: '1', name: 'Carlos Silva', role: 'CEO, Agência DigitalWeb', avatar: 'CS', content: 'PromptForge revolucionou nossa agência. Reduzimos o tempo de criação de briefings de 3 horas para 15 minutos.', rating: 5 },
  { id: '2', name: 'Juliana Costa', role: 'Freelancer', avatar: 'JC', content: 'Como freelancer, otimizar meu tempo é essencial. A plataforma me ajuda a entregar propostas profissionais em minutos.', rating: 5 },
  { id: '3', name: 'Rafael Oliveira', role: 'CTO, TechStart', avatar: 'RO', content: 'A qualidade dos prompts gerados pela IA da NVIDIA é impressionante. Detalhes que realmente fazem diferença no resultado final.', rating: 5 },
  { id: '4', name: 'Ana Beatriz', role: 'Designer Lead, UXLab', avatar: 'AB', content: 'Uso para criar briefings completos para minha equipe. A integração com Lovable e v0 é simplesmente fantástica.', rating: 5 },
  { id: '5', name: 'Pedro Santos', role: 'Desenvolvedor Full Stack', avatar: 'PS', content: 'Os prompts gerados já vêm com stack tecnológica, arquitetura e boas práticas. É como ter um arquiteto de software ajudando.', rating: 5 },
  { id: '6', name: 'Marina Lima', role: 'Head de Marketing, GrupoXYZ', avatar: 'ML', content: 'Geramos landing pages completas em dias, não semanas. O ROI da ferramenta se paga no primeiro projeto.', rating: 5 },
];

export const FAQ_ITEMS = [
  { question: 'O que é a PromptForge AI?', answer: 'A PromptForge AI é uma plataforma SaaS que utiliza inteligência artificial (NVIDIA AI) para gerar prompts profissionais, contratos, propostas comerciais, orçamentos e briefings para criação de sites, sistemas web, aplicativos e muito mais.' },
  { question: 'Como funciona o gerador de prompts?', answer: 'Nosso Wizard Inteligente guia você por 15 etapas: escolha do nicho, dados da empresa, objetivo, público-alvo, estilo visual, cores, tipografia, animações, estrutura, funcionalidades, tecnologias, plataforma de destino e briefing. No final, a IA da NVIDIA gera um prompt completo e otimizado.' },
  { question: 'Preciso de conhecimento técnico?', answer: 'Não. A plataforma foi projetada para ser intuitiva. Basta responder as perguntas do wizard e a IA cuida do resto. O resultado é um prompt profissional mesmo para quem não tem experiência técnica.' },
  { question: 'Quais plataformas são suportadas?', answer: 'Atualmente suportamos Lovable, Bolt.new, v0, Cursor, Claude Code e Replit. A IA adapta automaticamente o prompt para cada plataforma.' },
  { question: 'Posso gerar prompts em outros idiomas?', answer: 'Sim! Oferecemos geração em Português, Inglês, Espanhol, Francês, Alemão e Italiano.' },
  { question: 'Os contratos gerados têm validade jurídica?', answer: 'Nossos contratos seguem modelos profissionais e incluem cláusulas comuns do mercado. Recomendamos sempre a revisão por um advogado antes da assinatura.' },
  { question: 'Como funciona o plano gratuito?', answer: 'Oferecemos 7 dias de teste grátis no plano Pro, sem compromisso. Você pode cancelar quando quiser.' },
  { question: 'Quais formas de pagamento são aceitas?', answer: 'Aceitamos PIX, Cartão de Crédito (todas as bandeiras), Boleto Bancário e Transferência Bancária.' },
  { question: 'Posso mudar de plano depois?', answer: 'Sim! Você pode fazer upgrade ou downgrade do seu plano a qualquer momento. O valor é ajustado proporcionalmente.' },
  { question: 'Meus dados estão seguros?', answer: 'Sim. Utilizamos criptografia de ponta a ponta, autenticação segura, proteção contra SQL Injection, XSS e CSRF. Seguimos a LGPD.' },
];

export const ANIMATION_STAGES = [
  { text: 'npx promptforge --analyze', duration: 800 },
  { text: '  ✔ Analisando requisitos do projeto...', duration: 1200 },
  { text: 'npx promptforge --generate-palette', duration: 800 },
  { text: '  ✔ Gerando identidade visual...', duration: 1200 },
  { text: 'npx promptforge --build-components', duration: 800 },
  { text: '  ✔ Compilando componentes...', duration: 1200 },
  { text: 'npx promptforge --optimize', duration: 800 },
  { text: '  ✔ Otimizando prompt...', duration: 1200 },
  { text: 'npx promptforge --export', duration: 800 },
  { text: '  ✔ Prompt gerado com sucesso!', duration: 1000 },
];

export const DASHBOARD_DEFAULT_STATS = {
  totalProjects: 0,
  totalPrompts: 0,
  totalContracts: 0,
  totalProposals: 0,
  promptsThisMonth: 0,
  contractsThisMonth: 0,
  revenueThisMonth: 0,
  activeClients: 0,
};

export const MOCK_STATS = {
  totalProjects: 12,
  totalPrompts: 48,
  totalContracts: 15,
  totalProposals: 8,
  promptsThisMonth: 23,
  contractsThisMonth: 7,
  revenueThisMonth: 28450,
  activeClients: 9,
};

export const COLOR_PALETTES = [
  { name: 'Roxo Tech', colors: ['#A855F7', '#7C3AED', '#D946EF', '#1E1B4B', '#FFFFFF'] },
  { name: 'Verde Nature', colors: ['#10B981', '#059669', '#34D399', '#064E3B', '#FFFFFF'] },
  { name: 'Azul Corporate', colors: ['#3B82F6', '#2563EB', '#60A5FA', '#1E3A5F', '#FFFFFF'] },
  { name: 'Vermelho Power', colors: ['#EF4444', '#DC2626', '#F87171', '#7F1D1D', '#FFFFFF'] },
  { name: 'Laranja Fire', colors: ['#F97316', '#EA580C', '#FB923C', '#7C2D12', '#FFFFFF'] },
  { name: 'Rosa Pink', colors: ['#EC4899', '#DB2777', '#F472B6', '#831843', '#FFFFFF'] },
  { name: 'Ciano Fresh', colors: ['#06B6D4', '#0891B2', '#22D3EE', '#164E63', '#FFFFFF'] },
  { name: 'Amarelo Sun', colors: ['#EAB308', '#CA8A04', '#FDE047', '#713F12', '#FFFFFF'] },
  { name: 'Cinza Elegance', colors: ['#6B7280', '#4B5563', '#9CA3AF', '#111827', '#FFFFFF'] },
  { name: 'Dark Premium', colors: ['#A855F7', '#D946EF', '#1F2937', '#050505', '#FFFFFF'] },
];